/* Automatically @generated by tree-sitter */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 38
#define LARGE_STATE_COUNT 3
#define SYMBOL_COUNT 29
#define ALIAS_COUNT 0
#define TOKEN_COUNT 17
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 2
#define MAX_ALIAS_SEQUENCE_LENGTH 4
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 3
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  sym_word = 1,
  anon_sym_COLON = 2,
  anon_sym_SEMI = 3,
  anon_sym_type_COLON = 4,
  anon_sym_extern_COLON = 5,
  anon_sym_import_COLON = 6,
  anon_sym_export_COLON = 7,
  anon_sym_PIPE = 8,
  anon_sym_LPAREN = 9,
  anon_sym_RPAREN = 10,
  anon_sym_LBRACK = 11,
  anon_sym_RBRACK = 12,
  sym_int = 13,
  sym_float = 14,
  sym_string = 15,
  sym_comment = 16,
  sym_source_file = 17,
  sym__toplevel = 18,
  sym_word_definition = 19,
  sym_type_definition = 20,
  sym_extern_definition = 21,
  sym_import_definition = 22,
  sym_export_definition = 23,
  sym__atom = 24,
  sym_paren_group = 25,
  sym_bracket_group = 26,
  aux_sym_source_file_repeat1 = 27,
  aux_sym_word_definition_repeat1 = 28,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_word] = "word",
  [anon_sym_COLON] = ":",
  [anon_sym_SEMI] = ";",
  [anon_sym_type_COLON] = "type:",
  [anon_sym_extern_COLON] = "extern:",
  [anon_sym_import_COLON] = "import:",
  [anon_sym_export_COLON] = "export:",
  [anon_sym_PIPE] = "|",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [anon_sym_LBRACK] = "[",
  [anon_sym_RBRACK] = "]",
  [sym_int] = "int",
  [sym_float] = "float",
  [sym_string] = "string",
  [sym_comment] = "comment",
  [sym_source_file] = "source_file",
  [sym__toplevel] = "_toplevel",
  [sym_word_definition] = "word_definition",
  [sym_type_definition] = "type_definition",
  [sym_extern_definition] = "extern_definition",
  [sym_import_definition] = "import_definition",
  [sym_export_definition] = "export_definition",
  [sym__atom] = "_atom",
  [sym_paren_group] = "paren_group",
  [sym_bracket_group] = "bracket_group",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_word_definition_repeat1] = "word_definition_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_word] = sym_word,
  [anon_sym_COLON] = anon_sym_COLON,
  [anon_sym_SEMI] = anon_sym_SEMI,
  [anon_sym_type_COLON] = anon_sym_type_COLON,
  [anon_sym_extern_COLON] = anon_sym_extern_COLON,
  [anon_sym_import_COLON] = anon_sym_import_COLON,
  [anon_sym_export_COLON] = anon_sym_export_COLON,
  [anon_sym_PIPE] = anon_sym_PIPE,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [sym_int] = sym_int,
  [sym_float] = sym_float,
  [sym_string] = sym_string,
  [sym_comment] = sym_comment,
  [sym_source_file] = sym_source_file,
  [sym__toplevel] = sym__toplevel,
  [sym_word_definition] = sym_word_definition,
  [sym_type_definition] = sym_type_definition,
  [sym_extern_definition] = sym_extern_definition,
  [sym_import_definition] = sym_import_definition,
  [sym_export_definition] = sym_export_definition,
  [sym__atom] = sym__atom,
  [sym_paren_group] = sym_paren_group,
  [sym_bracket_group] = sym_bracket_group,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_word_definition_repeat1] = aux_sym_word_definition_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_word] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SEMI] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_type_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_extern_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_import_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_export_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PIPE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [sym_int] = {
    .visible = true,
    .named = true,
  },
  [sym_float] = {
    .visible = true,
    .named = true,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym__toplevel] = {
    .visible = false,
    .named = true,
  },
  [sym_word_definition] = {
    .visible = true,
    .named = true,
  },
  [sym_type_definition] = {
    .visible = true,
    .named = true,
  },
  [sym_extern_definition] = {
    .visible = true,
    .named = true,
  },
  [sym_import_definition] = {
    .visible = true,
    .named = true,
  },
  [sym_export_definition] = {
    .visible = true,
    .named = true,
  },
  [sym__atom] = {
    .visible = false,
    .named = true,
  },
  [sym_paren_group] = {
    .visible = true,
    .named = true,
  },
  [sym_bracket_group] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_word_definition_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_alias = 1,
  field_name = 2,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_alias] = "alias",
  [field_name] = "name",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
  [2] = {.index = 1, .length = 1},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_name, 1},
  [1] =
    {field_alias, 1},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
};

static const TSCharacterRange sym_word_character_set_1[] = {
  {0, 0x08}, {0x0e, 0x1f}, {'!', '!'}, {'#', '\''}, {'*', ':'}, {'<', 'Z'}, {'\\', '\\'}, {'^', '{'},
  {'}', 0x10ffff},
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(27);
      ADVANCE_MAP(
        '"', 2,
        '(', 35,
        ')', 36,
        '-', 54,
        ':', 57,
        ';', 29,
        '[', 37,
        '\\', 62,
        ']', 38,
        'e', 51,
        'i', 42,
        't', 52,
        '|', 34,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(58);
      if (lookahead != 0) ADVANCE(57);
      END_STATE();
    case 1:
      ADVANCE_MAP(
        '"', 2,
        '(', 35,
        ')', 36,
        '-', 54,
        ';', 29,
        '[', 37,
        '\\', 62,
        ']', 38,
        '|', 34,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(1);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(58);
      if (lookahead != 0) ADVANCE(57);
      END_STATE();
    case 2:
      if (lookahead == '"') ADVANCE(61);
      if (lookahead == '\\') ADVANCE(25);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(2);
      END_STATE();
    case 3:
      if (lookahead == ':') ADVANCE(30);
      END_STATE();
    case 4:
      if (lookahead == ':') ADVANCE(33);
      END_STATE();
    case 5:
      if (lookahead == ':') ADVANCE(31);
      END_STATE();
    case 6:
      if (lookahead == ':') ADVANCE(32);
      END_STATE();
    case 7:
      if (lookahead == '>') ADVANCE(57);
      END_STATE();
    case 8:
      if (lookahead == '\\') ADVANCE(62);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(8);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != '(' &&
          lookahead != ')' &&
          lookahead != ';' &&
          (lookahead < '[' || ']' < lookahead) &&
          lookahead != '|') ADVANCE(57);
      END_STATE();
    case 9:
      if (lookahead == 'e') ADVANCE(3);
      END_STATE();
    case 10:
      if (lookahead == 'e') ADVANCE(19);
      END_STATE();
    case 11:
      if (lookahead == 'm') ADVANCE(17);
      END_STATE();
    case 12:
      if (lookahead == 'n') ADVANCE(5);
      END_STATE();
    case 13:
      if (lookahead == 'o') ADVANCE(18);
      END_STATE();
    case 14:
      if (lookahead == 'o') ADVANCE(20);
      END_STATE();
    case 15:
      if (lookahead == 'p') ADVANCE(13);
      if (lookahead == 't') ADVANCE(10);
      END_STATE();
    case 16:
      if (lookahead == 'p') ADVANCE(9);
      END_STATE();
    case 17:
      if (lookahead == 'p') ADVANCE(14);
      END_STATE();
    case 18:
      if (lookahead == 'r') ADVANCE(21);
      END_STATE();
    case 19:
      if (lookahead == 'r') ADVANCE(12);
      END_STATE();
    case 20:
      if (lookahead == 'r') ADVANCE(22);
      END_STATE();
    case 21:
      if (lookahead == 't') ADVANCE(4);
      END_STATE();
    case 22:
      if (lookahead == 't') ADVANCE(6);
      END_STATE();
    case 23:
      if (lookahead == 'x') ADVANCE(15);
      END_STATE();
    case 24:
      if (lookahead == 'y') ADVANCE(16);
      END_STATE();
    case 25:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(2);
      END_STATE();
    case 26:
      if (eof) ADVANCE(27);
      if (lookahead == ':') ADVANCE(28);
      if (lookahead == '\\') ADVANCE(62);
      if (lookahead == 'e') ADVANCE(23);
      if (lookahead == 'i') ADVANCE(11);
      if (lookahead == 't') ADVANCE(24);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(26);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(anon_sym_SEMI);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(anon_sym_type_COLON);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(anon_sym_extern_COLON);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(anon_sym_import_COLON);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(anon_sym_export_COLON);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(anon_sym_PIPE);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(sym_word);
      if (lookahead == ':') ADVANCE(57);
      if (lookahead == '|') ADVANCE(7);
      if ((!eof && set_contains(sym_word_character_set_1, 9, lookahead))) ADVANCE(57);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(sym_word);
      if (lookahead == 'e') ADVANCE(39);
      if (lookahead == '|') ADVANCE(7);
      if ((!eof && set_contains(sym_word_character_set_1, 9, lookahead))) ADVANCE(57);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(sym_word);
      if (lookahead == 'e') ADVANCE(49);
      if (lookahead == '|') ADVANCE(7);
      if ((!eof && set_contains(sym_word_character_set_1, 9, lookahead))) ADVANCE(57);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(sym_word);
      if (lookahead == 'm') ADVANCE(46);
      if (lookahead == '|') ADVANCE(7);
      if ((!eof && set_contains(sym_word_character_set_1, 9, lookahead))) ADVANCE(57);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(sym_word);
      if (lookahead == 'n') ADVANCE(39);
      if (lookahead == '|') ADVANCE(7);
      if ((!eof && set_contains(sym_word_character_set_1, 9, lookahead))) ADVANCE(57);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(sym_word);
      if (lookahead == 'o') ADVANCE(48);
      if (lookahead == '|') ADVANCE(7);
      if ((!eof && set_contains(sym_word_character_set_1, 9, lookahead))) ADVANCE(57);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(sym_word);
      if (lookahead == 'p') ADVANCE(44);
      if (lookahead == 't') ADVANCE(41);
      if (lookahead == '|') ADVANCE(7);
      if ((!eof && set_contains(sym_word_character_set_1, 9, lookahead))) ADVANCE(57);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(sym_word);
      if (lookahead == 'p') ADVANCE(44);
      if (lookahead == '|') ADVANCE(7);
      if ((!eof && set_contains(sym_word_character_set_1, 9, lookahead))) ADVANCE(57);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(sym_word);
      if (lookahead == 'p') ADVANCE(40);
      if (lookahead == '|') ADVANCE(7);
      if ((!eof && set_contains(sym_word_character_set_1, 9, lookahead))) ADVANCE(57);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(sym_word);
      if (lookahead == 'r') ADVANCE(50);
      if (lookahead == '|') ADVANCE(7);
      if ((!eof && set_contains(sym_word_character_set_1, 9, lookahead))) ADVANCE(57);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(sym_word);
      if (lookahead == 'r') ADVANCE(43);
      if (lookahead == '|') ADVANCE(7);
      if ((!eof && set_contains(sym_word_character_set_1, 9, lookahead))) ADVANCE(57);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(sym_word);
      if (lookahead == 't') ADVANCE(39);
      if (lookahead == '|') ADVANCE(7);
      if ((!eof && set_contains(sym_word_character_set_1, 9, lookahead))) ADVANCE(57);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(sym_word);
      if (lookahead == 'x') ADVANCE(45);
      if (lookahead == '|') ADVANCE(7);
      if ((!eof && set_contains(sym_word_character_set_1, 9, lookahead))) ADVANCE(57);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(sym_word);
      if (lookahead == 'y') ADVANCE(47);
      if (lookahead == '|') ADVANCE(7);
      if ((!eof && set_contains(sym_word_character_set_1, 9, lookahead))) ADVANCE(57);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(sym_word);
      if (lookahead == '|') ADVANCE(7);
      if (lookahead == '+' ||
          lookahead == '-') ADVANCE(56);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(60);
      if ((!eof && set_contains(sym_word_character_set_1, 9, lookahead))) ADVANCE(57);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(sym_word);
      if (lookahead == '|') ADVANCE(7);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(58);
      if ((!eof && set_contains(sym_word_character_set_1, 9, lookahead))) ADVANCE(57);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(sym_word);
      if (lookahead == '|') ADVANCE(7);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(59);
      if ((!eof && set_contains(sym_word_character_set_1, 9, lookahead))) ADVANCE(57);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(sym_word);
      if (lookahead == '|') ADVANCE(7);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(60);
      if ((!eof && set_contains(sym_word_character_set_1, 9, lookahead))) ADVANCE(57);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(sym_word);
      if (lookahead == '|') ADVANCE(7);
      if ((!eof && set_contains(sym_word_character_set_1, 9, lookahead))) ADVANCE(57);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(sym_int);
      if (lookahead == '.') ADVANCE(55);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(58);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(sym_float);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(53);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(59);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(sym_float);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(60);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(sym_string);
      END_STATE();
    case 62:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(63);
      END_STATE();
    case 63:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(63);
      END_STATE();
    default:
      return false;
  }
}

static bool ts_lex_keywords(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 26},
  [2] = {.lex_state = 1},
  [3] = {.lex_state = 26},
  [4] = {.lex_state = 26},
  [5] = {.lex_state = 1},
  [6] = {.lex_state = 1},
  [7] = {.lex_state = 1},
  [8] = {.lex_state = 1},
  [9] = {.lex_state = 1},
  [10] = {.lex_state = 1},
  [11] = {.lex_state = 1},
  [12] = {.lex_state = 1},
  [13] = {.lex_state = 1},
  [14] = {.lex_state = 1},
  [15] = {.lex_state = 1},
  [16] = {.lex_state = 1},
  [17] = {.lex_state = 1},
  [18] = {.lex_state = 1},
  [19] = {.lex_state = 1},
  [20] = {.lex_state = 1},
  [21] = {.lex_state = 1},
  [22] = {.lex_state = 1},
  [23] = {.lex_state = 26},
  [24] = {.lex_state = 26},
  [25] = {.lex_state = 26},
  [26] = {.lex_state = 26},
  [27] = {.lex_state = 26},
  [28] = {.lex_state = 26},
  [29] = {.lex_state = 26},
  [30] = {.lex_state = 26},
  [31] = {.lex_state = 26},
  [32] = {.lex_state = 26},
  [33] = {.lex_state = 8},
  [34] = {.lex_state = 8},
  [35] = {.lex_state = 0},
  [36] = {.lex_state = 8},
  [37] = {.lex_state = 8},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_word] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [anon_sym_SEMI] = ACTIONS(1),
    [anon_sym_type_COLON] = ACTIONS(1),
    [anon_sym_extern_COLON] = ACTIONS(1),
    [anon_sym_import_COLON] = ACTIONS(1),
    [anon_sym_export_COLON] = ACTIONS(1),
    [anon_sym_PIPE] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [sym_int] = ACTIONS(1),
    [sym_float] = ACTIONS(1),
    [sym_string] = ACTIONS(1),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(35),
    [sym__toplevel] = STATE(3),
    [sym_word_definition] = STATE(3),
    [sym_type_definition] = STATE(3),
    [sym_extern_definition] = STATE(3),
    [sym_import_definition] = STATE(3),
    [sym_export_definition] = STATE(3),
    [aux_sym_source_file_repeat1] = STATE(3),
    [ts_builtin_sym_end] = ACTIONS(5),
    [anon_sym_COLON] = ACTIONS(7),
    [anon_sym_type_COLON] = ACTIONS(9),
    [anon_sym_extern_COLON] = ACTIONS(11),
    [anon_sym_import_COLON] = ACTIONS(13),
    [anon_sym_export_COLON] = ACTIONS(15),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(2)] = {
    [sym__atom] = STATE(2),
    [sym_paren_group] = STATE(2),
    [sym_bracket_group] = STATE(2),
    [aux_sym_word_definition_repeat1] = STATE(2),
    [sym_word] = ACTIONS(17),
    [anon_sym_SEMI] = ACTIONS(20),
    [anon_sym_PIPE] = ACTIONS(22),
    [anon_sym_LPAREN] = ACTIONS(25),
    [anon_sym_RPAREN] = ACTIONS(20),
    [anon_sym_LBRACK] = ACTIONS(28),
    [anon_sym_RBRACK] = ACTIONS(20),
    [sym_int] = ACTIONS(17),
    [sym_float] = ACTIONS(22),
    [sym_string] = ACTIONS(22),
    [sym_comment] = ACTIONS(3),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      anon_sym_COLON,
    ACTIONS(9), 1,
      anon_sym_type_COLON,
    ACTIONS(11), 1,
      anon_sym_extern_COLON,
    ACTIONS(13), 1,
      anon_sym_import_COLON,
    ACTIONS(15), 1,
      anon_sym_export_COLON,
    ACTIONS(31), 1,
      ts_builtin_sym_end,
    STATE(4), 7,
      sym__toplevel,
      sym_word_definition,
      sym_type_definition,
      sym_extern_definition,
      sym_import_definition,
      sym_export_definition,
      aux_sym_source_file_repeat1,
  [31] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(33), 1,
      ts_builtin_sym_end,
    ACTIONS(35), 1,
      anon_sym_COLON,
    ACTIONS(38), 1,
      anon_sym_type_COLON,
    ACTIONS(41), 1,
      anon_sym_extern_COLON,
    ACTIONS(44), 1,
      anon_sym_import_COLON,
    ACTIONS(47), 1,
      anon_sym_export_COLON,
    STATE(4), 7,
      sym__toplevel,
      sym_word_definition,
      sym_type_definition,
      sym_extern_definition,
      sym_import_definition,
      sym_export_definition,
      aux_sym_source_file_repeat1,
  [62] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(52), 1,
      anon_sym_SEMI,
    ACTIONS(56), 1,
      anon_sym_LPAREN,
    ACTIONS(58), 1,
      anon_sym_LBRACK,
    ACTIONS(50), 2,
      sym_word,
      sym_int,
    ACTIONS(54), 3,
      anon_sym_PIPE,
      sym_float,
      sym_string,
    STATE(2), 4,
      sym__atom,
      sym_paren_group,
      sym_bracket_group,
      aux_sym_word_definition_repeat1,
  [90] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(56), 1,
      anon_sym_LPAREN,
    ACTIONS(58), 1,
      anon_sym_LBRACK,
    ACTIONS(62), 1,
      anon_sym_SEMI,
    ACTIONS(60), 2,
      sym_word,
      sym_int,
    ACTIONS(64), 3,
      anon_sym_PIPE,
      sym_float,
      sym_string,
    STATE(5), 4,
      sym__atom,
      sym_paren_group,
      sym_bracket_group,
      aux_sym_word_definition_repeat1,
  [118] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(56), 1,
      anon_sym_LPAREN,
    ACTIONS(58), 1,
      anon_sym_LBRACK,
    ACTIONS(68), 1,
      anon_sym_SEMI,
    ACTIONS(66), 2,
      sym_word,
      sym_int,
    ACTIONS(70), 3,
      anon_sym_PIPE,
      sym_float,
      sym_string,
    STATE(17), 4,
      sym__atom,
      sym_paren_group,
      sym_bracket_group,
      aux_sym_word_definition_repeat1,
  [146] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(56), 1,
      anon_sym_LPAREN,
    ACTIONS(58), 1,
      anon_sym_LBRACK,
    ACTIONS(76), 1,
      anon_sym_RBRACK,
    ACTIONS(72), 2,
      sym_word,
      sym_int,
    ACTIONS(74), 3,
      anon_sym_PIPE,
      sym_float,
      sym_string,
    STATE(18), 4,
      sym__atom,
      sym_paren_group,
      sym_bracket_group,
      aux_sym_word_definition_repeat1,
  [174] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(56), 1,
      anon_sym_LPAREN,
    ACTIONS(58), 1,
      anon_sym_LBRACK,
    ACTIONS(80), 1,
      anon_sym_SEMI,
    ACTIONS(78), 2,
      sym_word,
      sym_int,
    ACTIONS(82), 3,
      anon_sym_PIPE,
      sym_float,
      sym_string,
    STATE(13), 4,
      sym__atom,
      sym_paren_group,
      sym_bracket_group,
      aux_sym_word_definition_repeat1,
  [202] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(56), 1,
      anon_sym_LPAREN,
    ACTIONS(58), 1,
      anon_sym_LBRACK,
    ACTIONS(86), 1,
      anon_sym_SEMI,
    ACTIONS(84), 2,
      sym_word,
      sym_int,
    ACTIONS(88), 3,
      anon_sym_PIPE,
      sym_float,
      sym_string,
    STATE(14), 4,
      sym__atom,
      sym_paren_group,
      sym_bracket_group,
      aux_sym_word_definition_repeat1,
  [230] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(56), 1,
      anon_sym_LPAREN,
    ACTIONS(58), 1,
      anon_sym_LBRACK,
    ACTIONS(92), 1,
      anon_sym_SEMI,
    ACTIONS(90), 2,
      sym_word,
      sym_int,
    ACTIONS(94), 3,
      anon_sym_PIPE,
      sym_float,
      sym_string,
    STATE(16), 4,
      sym__atom,
      sym_paren_group,
      sym_bracket_group,
      aux_sym_word_definition_repeat1,
  [258] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(56), 1,
      anon_sym_LPAREN,
    ACTIONS(58), 1,
      anon_sym_LBRACK,
    ACTIONS(100), 1,
      anon_sym_RPAREN,
    ACTIONS(96), 2,
      sym_word,
      sym_int,
    ACTIONS(98), 3,
      anon_sym_PIPE,
      sym_float,
      sym_string,
    STATE(15), 4,
      sym__atom,
      sym_paren_group,
      sym_bracket_group,
      aux_sym_word_definition_repeat1,
  [286] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(56), 1,
      anon_sym_LPAREN,
    ACTIONS(58), 1,
      anon_sym_LBRACK,
    ACTIONS(102), 1,
      anon_sym_SEMI,
    ACTIONS(50), 2,
      sym_word,
      sym_int,
    ACTIONS(54), 3,
      anon_sym_PIPE,
      sym_float,
      sym_string,
    STATE(2), 4,
      sym__atom,
      sym_paren_group,
      sym_bracket_group,
      aux_sym_word_definition_repeat1,
  [314] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(56), 1,
      anon_sym_LPAREN,
    ACTIONS(58), 1,
      anon_sym_LBRACK,
    ACTIONS(104), 1,
      anon_sym_SEMI,
    ACTIONS(50), 2,
      sym_word,
      sym_int,
    ACTIONS(54), 3,
      anon_sym_PIPE,
      sym_float,
      sym_string,
    STATE(2), 4,
      sym__atom,
      sym_paren_group,
      sym_bracket_group,
      aux_sym_word_definition_repeat1,
  [342] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(56), 1,
      anon_sym_LPAREN,
    ACTIONS(58), 1,
      anon_sym_LBRACK,
    ACTIONS(106), 1,
      anon_sym_RPAREN,
    ACTIONS(50), 2,
      sym_word,
      sym_int,
    ACTIONS(54), 3,
      anon_sym_PIPE,
      sym_float,
      sym_string,
    STATE(2), 4,
      sym__atom,
      sym_paren_group,
      sym_bracket_group,
      aux_sym_word_definition_repeat1,
  [370] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(56), 1,
      anon_sym_LPAREN,
    ACTIONS(58), 1,
      anon_sym_LBRACK,
    ACTIONS(108), 1,
      anon_sym_SEMI,
    ACTIONS(50), 2,
      sym_word,
      sym_int,
    ACTIONS(54), 3,
      anon_sym_PIPE,
      sym_float,
      sym_string,
    STATE(2), 4,
      sym__atom,
      sym_paren_group,
      sym_bracket_group,
      aux_sym_word_definition_repeat1,
  [398] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(56), 1,
      anon_sym_LPAREN,
    ACTIONS(58), 1,
      anon_sym_LBRACK,
    ACTIONS(110), 1,
      anon_sym_SEMI,
    ACTIONS(50), 2,
      sym_word,
      sym_int,
    ACTIONS(54), 3,
      anon_sym_PIPE,
      sym_float,
      sym_string,
    STATE(2), 4,
      sym__atom,
      sym_paren_group,
      sym_bracket_group,
      aux_sym_word_definition_repeat1,
  [426] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(56), 1,
      anon_sym_LPAREN,
    ACTIONS(58), 1,
      anon_sym_LBRACK,
    ACTIONS(112), 1,
      anon_sym_RBRACK,
    ACTIONS(50), 2,
      sym_word,
      sym_int,
    ACTIONS(54), 3,
      anon_sym_PIPE,
      sym_float,
      sym_string,
    STATE(2), 4,
      sym__atom,
      sym_paren_group,
      sym_bracket_group,
      aux_sym_word_definition_repeat1,
  [454] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(114), 2,
      sym_word,
      sym_int,
    ACTIONS(116), 8,
      anon_sym_SEMI,
      anon_sym_PIPE,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      sym_float,
      sym_string,
  [472] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(118), 2,
      sym_word,
      sym_int,
    ACTIONS(120), 8,
      anon_sym_SEMI,
      anon_sym_PIPE,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      sym_float,
      sym_string,
  [490] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(122), 2,
      sym_word,
      sym_int,
    ACTIONS(124), 8,
      anon_sym_SEMI,
      anon_sym_PIPE,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      sym_float,
      sym_string,
  [508] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(126), 2,
      sym_word,
      sym_int,
    ACTIONS(128), 8,
      anon_sym_SEMI,
      anon_sym_PIPE,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      sym_float,
      sym_string,
  [526] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(130), 6,
      ts_builtin_sym_end,
      anon_sym_COLON,
      anon_sym_type_COLON,
      anon_sym_extern_COLON,
      anon_sym_import_COLON,
      anon_sym_export_COLON,
  [538] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(132), 6,
      ts_builtin_sym_end,
      anon_sym_COLON,
      anon_sym_type_COLON,
      anon_sym_extern_COLON,
      anon_sym_import_COLON,
      anon_sym_export_COLON,
  [550] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(134), 6,
      ts_builtin_sym_end,
      anon_sym_COLON,
      anon_sym_type_COLON,
      anon_sym_extern_COLON,
      anon_sym_import_COLON,
      anon_sym_export_COLON,
  [562] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(136), 6,
      ts_builtin_sym_end,
      anon_sym_COLON,
      anon_sym_type_COLON,
      anon_sym_extern_COLON,
      anon_sym_import_COLON,
      anon_sym_export_COLON,
  [574] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(138), 6,
      ts_builtin_sym_end,
      anon_sym_COLON,
      anon_sym_type_COLON,
      anon_sym_extern_COLON,
      anon_sym_import_COLON,
      anon_sym_export_COLON,
  [586] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(140), 6,
      ts_builtin_sym_end,
      anon_sym_COLON,
      anon_sym_type_COLON,
      anon_sym_extern_COLON,
      anon_sym_import_COLON,
      anon_sym_export_COLON,
  [598] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(142), 6,
      ts_builtin_sym_end,
      anon_sym_COLON,
      anon_sym_type_COLON,
      anon_sym_extern_COLON,
      anon_sym_import_COLON,
      anon_sym_export_COLON,
  [610] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(144), 6,
      ts_builtin_sym_end,
      anon_sym_COLON,
      anon_sym_type_COLON,
      anon_sym_extern_COLON,
      anon_sym_import_COLON,
      anon_sym_export_COLON,
  [622] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(146), 6,
      ts_builtin_sym_end,
      anon_sym_COLON,
      anon_sym_type_COLON,
      anon_sym_extern_COLON,
      anon_sym_import_COLON,
      anon_sym_export_COLON,
  [634] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(148), 6,
      ts_builtin_sym_end,
      anon_sym_COLON,
      anon_sym_type_COLON,
      anon_sym_extern_COLON,
      anon_sym_import_COLON,
      anon_sym_export_COLON,
  [646] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(150), 1,
      sym_word,
  [653] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(152), 1,
      sym_word,
  [660] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(154), 1,
      ts_builtin_sym_end,
  [667] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(156), 1,
      sym_word,
  [674] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(158), 1,
      sym_word,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(3)] = 0,
  [SMALL_STATE(4)] = 31,
  [SMALL_STATE(5)] = 62,
  [SMALL_STATE(6)] = 90,
  [SMALL_STATE(7)] = 118,
  [SMALL_STATE(8)] = 146,
  [SMALL_STATE(9)] = 174,
  [SMALL_STATE(10)] = 202,
  [SMALL_STATE(11)] = 230,
  [SMALL_STATE(12)] = 258,
  [SMALL_STATE(13)] = 286,
  [SMALL_STATE(14)] = 314,
  [SMALL_STATE(15)] = 342,
  [SMALL_STATE(16)] = 370,
  [SMALL_STATE(17)] = 398,
  [SMALL_STATE(18)] = 426,
  [SMALL_STATE(19)] = 454,
  [SMALL_STATE(20)] = 472,
  [SMALL_STATE(21)] = 490,
  [SMALL_STATE(22)] = 508,
  [SMALL_STATE(23)] = 526,
  [SMALL_STATE(24)] = 538,
  [SMALL_STATE(25)] = 550,
  [SMALL_STATE(26)] = 562,
  [SMALL_STATE(27)] = 574,
  [SMALL_STATE(28)] = 586,
  [SMALL_STATE(29)] = 598,
  [SMALL_STATE(30)] = 610,
  [SMALL_STATE(31)] = 622,
  [SMALL_STATE(32)] = 634,
  [SMALL_STATE(33)] = 646,
  [SMALL_STATE(34)] = 653,
  [SMALL_STATE(35)] = 660,
  [SMALL_STATE(36)] = 667,
  [SMALL_STATE(37)] = 674,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [17] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_word_definition_repeat1, 2, 0, 0), SHIFT_REPEAT(2),
  [20] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_word_definition_repeat1, 2, 0, 0),
  [22] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_word_definition_repeat1, 2, 0, 0), SHIFT_REPEAT(2),
  [25] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_word_definition_repeat1, 2, 0, 0), SHIFT_REPEAT(12),
  [28] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_word_definition_repeat1, 2, 0, 0), SHIFT_REPEAT(8),
  [31] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [33] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [35] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(33),
  [38] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(34),
  [41] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(36),
  [44] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(37),
  [47] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(6),
  [50] = {.entry = {.count = 1, .reusable = false}}, SHIFT(2),
  [52] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [54] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [56] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [58] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [60] = {.entry = {.count = 1, .reusable = false}}, SHIFT(5),
  [62] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [64] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [66] = {.entry = {.count = 1, .reusable = false}}, SHIFT(17),
  [68] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [70] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [72] = {.entry = {.count = 1, .reusable = false}}, SHIFT(18),
  [74] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [76] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [78] = {.entry = {.count = 1, .reusable = false}}, SHIFT(13),
  [80] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [82] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [84] = {.entry = {.count = 1, .reusable = false}}, SHIFT(14),
  [86] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [88] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [90] = {.entry = {.count = 1, .reusable = false}}, SHIFT(16),
  [92] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [94] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [96] = {.entry = {.count = 1, .reusable = false}}, SHIFT(15),
  [98] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [100] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [102] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [104] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [106] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [108] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [110] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [112] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [114] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_bracket_group, 2, 0, 0),
  [116] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_bracket_group, 2, 0, 0),
  [118] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_paren_group, 2, 0, 0),
  [120] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_paren_group, 2, 0, 0),
  [122] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_paren_group, 3, 0, 0),
  [124] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_paren_group, 3, 0, 0),
  [126] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_bracket_group, 3, 0, 0),
  [128] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_bracket_group, 3, 0, 0),
  [130] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_word_definition, 3, 0, 1),
  [132] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_export_definition, 2, 0, 0),
  [134] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type_definition, 3, 0, 1),
  [136] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_import_definition, 3, 0, 2),
  [138] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_extern_definition, 3, 0, 1),
  [140] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_export_definition, 3, 0, 0),
  [142] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_word_definition, 4, 0, 1),
  [144] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_extern_definition, 4, 0, 1),
  [146] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type_definition, 4, 0, 1),
  [148] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_import_definition, 4, 0, 2),
  [150] = {.entry = {.count = 1, .reusable = false}}, SHIFT(9),
  [152] = {.entry = {.count = 1, .reusable = false}}, SHIFT(10),
  [154] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [156] = {.entry = {.count = 1, .reusable = false}}, SHIFT(11),
  [158] = {.entry = {.count = 1, .reusable = false}}, SHIFT(7),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_sooth(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .keyword_lex_fn = ts_lex_keywords,
    .keyword_capture_token = sym_word,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
