//! Builtin operator table and type predicates: `Sig`/`Overload` resolution,
//! the concrete `builtin_table()` rows `check_operator` dispatches through,
//! and `is_copy`/`is_linear`/`contains_reference`. Engine-independent leaf: no
//! `Ctx`, `Scope`, or `Moves` dependency, so nothing here can see the borrow
//! checker.

use std::collections::HashMap;

use super::*;

/// A word's typed stack effect: the concrete input and output slot types,
/// deepest-first (leftmost in `( … )` is deepest on the stack).
#[derive(Debug, Clone, PartialEq)]
pub struct Sig {
    pub inputs: Vec<Type>,
    pub outputs: Vec<Type>,
}

/// The typed effect of a declared word.
pub fn sig_of(effect: &StackEffect) -> Sig {
    Sig {
        inputs: effect.inputs.iter().map(|s| s.ty).collect(),
        outputs: effect.outputs.iter().map(|s| s.ty).collect(),
    }
}

/// Slice 8a fix 1 (R1): one candidate registered under a name that may carry
/// more than one -- an overload set. The word env's value type widened from a
/// single `Sig` to `Vec<Overload>` so a name with several same-arity,
/// differing-input-type candidates (R1/R4 already guarantee at most one can
/// match a given call's operand types) keeps every one of them reachable,
/// rather than the env's old bare `HashMap<String, Vec<Overload>>` silently keeping
/// only the last inserted. `symbol` is the distinct lowering symbol this
/// candidate's body was minted under (`ast::overload_symbols`): equal to the
/// surface name unless this name has more than one candidate in scope.
#[derive(Debug, Clone)]
pub struct Overload {
    pub sig: Sig,
    pub symbol: String,
}

/// R1/R2: the one candidate among `candidates` whose declared inputs exactly
/// match `operands`, if any. R1's widened duplicate-word key guarantees at
/// most one: two candidates registered under one name in scope never share
/// input types.
pub(super) fn resolve_overload<'a>(
    candidates: &'a [Overload],
    operands: &[Type],
) -> Option<&'a Overload> {
    candidates.iter().find(|o| o.sig.inputs == operands)
}

/// One builtin overload candidate (slice 8a, Q-A): the concrete input types
/// it matches (deepest-first), the concrete outputs it produces, and the
/// codegen a call resolving to it emits.
///
/// Only `inputs`/`outputs` are load-bearing: they are what the checker's
/// dispatch reads. `lower` records which instruction each row's retired
/// `check_operator` arm produced, but nothing consumes it -- lowering reaches
/// a builtin through `lower_call`'s name-directed arms and an overload
/// through the per-`Span` resolved-symbol record, neither of which consults
/// this table. It is unused weight kept only because it documents the
/// name-to-codegen mapping; delete it, and the unit tests that only assert
/// its shape, unless a table-driven lowering actually arrives to want it.
#[derive(Debug, Clone)]
pub struct BuiltinRow {
    pub inputs: Vec<Type>,
    pub outputs: Vec<Type>,
    #[allow(dead_code)]
    pub lower: BuiltinLower,
}

/// The codegen a resolved builtin row emits: one variant per distinct
/// instruction the type-directed `check_operator` arms produced. This is why
/// a row is not a `Sig` (Q-A): several rows for one name can share the
/// `(inputs, outputs)` shape and still differ here.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum BuiltinLower {
    Add,
    Sub,
    Mul,
    DivFloat,
    Mod,
    And,
    Or,
    Xor,
    Not,
    Shl,
    Shr,
    Cmp(crate::ir::CmpOp),
    Max,
    MaxTotal,
}

/// The numeric types the arithmetic tower and comparisons range over (the
/// eight fixed-width ints, `usize`/`isize`, and the two floats): `is_numeric`
/// made concrete as a list so the table below is generated by iteration
/// rather than hand-typed per row.
pub(super) fn numeric_types() -> Vec<Type> {
    [
        "i8", "i16", "i32", "i64", "u8", "u16", "u32", "u64", "usize", "isize", "f32", "f64",
    ]
    .iter()
    .map(|n| Type::from_name(n).expect("a builtin numeric type name"))
    .collect()
}

/// The integer subset (the eight widths plus `usize`/`isize`, D7): the domain
/// of `mod`/`and`/`or`/`xor`/`not`/`shl`/`shr`/`max`.
pub(super) fn int_types() -> Vec<Type> {
    numeric_types().into_iter().filter(|t| t.is_int()).collect()
}

/// The two float types: the domain of `div` and `max-total`.
pub(super) fn float_types() -> Vec<Type> {
    numeric_types()
        .into_iter()
        .filter(|t| t.is_float())
        .collect()
}

/// Slice 10c (R-P3-3): the six comparison primitives and the `CmpOp` each
/// lowers, named once so the checker table, the operator-name lists and the
/// lowering dispatch cannot drift apart.
pub(crate) const COMPARISON_PRIMITIVES: [(&str, crate::ir::CmpOp); 6] = [
    ("ueq", crate::ir::CmpOp::Eq),
    ("ult", crate::ir::CmpOp::Lt),
    ("ugt", crate::ir::CmpOp::Gt),
    ("ulte", crate::ir::CmpOp::Le),
    ("ugte", crate::ir::CmpOp::Ge),
    ("une", crate::ir::CmpOp::Ne),
];

/// The builtin overload table (slice 8a, Q-A): every concrete row a builtin
/// operator resolves to, keyed by operator name, each name carrying one row
/// per operand-type shape it accepts. `check_operator` does an exact-type
/// lookup here first (so a user overload of a builtin name can shadow a call
/// site, phase 2); the numeric operand-class coercion and its per-operator
/// diagnostics remain a hand-written fallback reached only on an exact miss
/// (Q-B). The generic builtins (`len`/`fill`/`cstr`, the `>T` conversions,
/// the shuffles) are carved out and stay in their own dispatchers (Q-A, R0).
pub fn builtin_table() -> HashMap<String, Vec<BuiltinRow>> {
    let mut table: HashMap<String, Vec<BuiltinRow>> = HashMap::new();
    let mut row = |name: &str, inputs: Vec<Type>, outputs: Vec<Type>, lower: BuiltinLower| {
        table.entry(name.to_string()).or_default().push(BuiltinRow {
            inputs,
            outputs,
            lower,
        });
    };
    for ty in numeric_types() {
        row("add", vec![ty, ty], vec![ty], BuiltinLower::Add);
        row("sub", vec![ty, ty], vec![ty], BuiltinLower::Sub);
        row("mul", vec![ty, ty], vec![ty], BuiltinLower::Mul);
        // Slice 10c (R-P3-3): the comparison *primitives*, each yielding the
        // 32-bit flag `branch` consumes. The `u` prefix marks the raw-flag
        // layer, not an unsigned-operand variant: there is exactly one
        // primitive per comparison shape and it derives signed / unsigned /
        // float behaviour from its operand type at lowering, exactly as the
        // rows it replaces did. `eq`/`lt`/... are now ordinary `lib/` words over
        // these, so the six surface names have *left* this table -- which is
        // also what lets them be `inline` (`check_inline_declaration`'s
        // builtin-name gate keys on membership here).
        for (op, cmp) in COMPARISON_PRIMITIVES {
            row(op, vec![ty, ty], vec![Type::U32], BuiltinLower::Cmp(cmp));
        }
    }
    for ty in float_types() {
        row("div", vec![ty, ty], vec![ty], BuiltinLower::DivFloat);
        row("max-total", vec![ty, ty], vec![ty], BuiltinLower::MaxTotal);
    }
    for ty in int_types() {
        row("mod", vec![ty, ty], vec![ty], BuiltinLower::Mod);
        row("and", vec![ty, ty], vec![ty], BuiltinLower::And);
        row("or", vec![ty, ty], vec![ty], BuiltinLower::Or);
        row("xor", vec![ty, ty], vec![ty], BuiltinLower::Xor);
        row("not", vec![ty], vec![ty], BuiltinLower::Not);
        row("shl", vec![ty, Type::I64], vec![ty], BuiltinLower::Shl);
        row("shr", vec![ty, Type::I64], vec![ty], BuiltinLower::Shr);
        row("max", vec![ty, ty], vec![ty], BuiltinLower::Max);
    }
    table
}

/// Whether `name` is a builtin *operator*: one of the names `check_operator`
/// resolves against `BUILTIN_TABLE`. A user word declared under one of these
/// names is an overload of it, and 8a dispatch reaches an overload only through
/// the call site's recorded candidate, never by the literal name.
pub(crate) fn is_builtin_operator_name(name: &str) -> bool {
    BUILTIN_TABLE.contains_key(name)
}

/// The builtin table, built once. `check_operator` consults it on every
/// operator occurrence; `builtin_table()` itself rebuilds a fresh map for the
/// callers that own theirs (`check/declarations.rs`, the tests).
pub(super) static BUILTIN_TABLE: std::sync::LazyLock<HashMap<String, Vec<BuiltinRow>>> =
    std::sync::LazyLock::new(builtin_table);

/// R2/R7: whether `ty` is `Copy` (freely duplicated and discarded) rather than
/// linear (used exactly once, disposed by `drop`). A struct or enum is linear
/// iff any field/variant-payload field is (transitively), so a
/// struct-of-struct-of-resource or an enum carrying one is linear too.
/// `structs`/`enums` resolve a `Type::Struct`/`Type::Enum`'s fields; neither
/// can recurse into itself (`check_recursion` rejects that first), so this
/// always terminates.
///
/// R3 (slice 8b): a struct with a user `drop` overload is linear whatever its
/// fields say — a resource wrapping one `i64` would otherwise be `Copy` by
/// the structural fold alone, and so silently duplicated and forgotten.
pub fn is_copy(ty: Type, structs: &[StructDecl], enums: &[EnumDecl], arrays: &[ArrayDecl]) -> bool {
    match ty {
        Type::Struct(id, _) if structs[id.index()].has_drop_overload => false,
        Type::Struct(id, _) => structs[id.index()]
            .fields
            .iter()
            .all(|(_, field_ty)| is_copy(*field_ty, structs, enums, arrays)),
        Type::Enum(id, _) => enums[id.index()]
            .variants
            .iter()
            .flat_map(|v| v.fields.iter())
            .all(|(_, field_ty)| is_copy(*field_ty, structs, enums, arrays)),
        Type::Array(id, _) => is_copy(arrays[id.index()].element, structs, enums, arrays),
        // Always linear regardless of payload, so no payload lookup here.
        Type::OwnedCell(_, _) => false,
        // A shared reference is freely duplicated and discarded; a mutable one
        // is not (the exclusivity rule, which `dup`'s Copy gate already enforces).
        Type::Ref(_, mutable, _) => !mutable,
        // P7 slice 3c (R4): a slice splits by mutability exactly as a
        // reference does, and for the same reason -- duplicating a mutable view
        // would let two names mutate through one exclusive borrow. The
        // element's own `Copy`-ness is irrelevant (the view owns nothing), so
        // there is no registry lookup here. The `_ => true` wildcard below
        // would make a `!Slice[T]` freely duplicable and break exclusivity
        // outright, which is why this arm is anchored rather than left to it.
        Type::Slice(_, mutable, _) => !mutable,
        // P7.S3h: an `owning` closure carries a disposal obligation for what it
        // captured, and only running the body can discharge it -- so the value
        // is linear, and `call` (which pops its receiver) is its consuming use.
        // Anchored above the wildcard for the same reason `!Slice[T]` is: the
        // wildcard would make it freely duplicable and forgettable, which is
        // exactly the leak this marker exists to prevent. Plain
        // `Type::Quotation` still falls to the wildcard and stays `Copy`.
        Type::OwningQuotation(_) => false,
        // P7b.S1 (S1-16 gap): a `CtorImage` is not a concrete value type
        // (S1-12) -- it never reaches a value position a real program can
        // `dup`/`drop`, since every real consumer routes a bare one to
        // S1-15.g first. Anchored above the wildcard rather than left to it,
        // matching `OwningQuotation`/`Slice` above: the wildcard would
        // silently call it freely duplicable.
        Type::CtorImage(_, _) => false,
        _ => true,
    }
}

/// Whether `ty` carries an exactly-once obligation: used exactly once,
/// disposed by `drop`, tracked by `Moves`. This is *not* the negation of
/// `is_copy`: `&!T` is neither `Copy` nor linear, so it is duplicated
/// by nothing and owed to nothing — a reference local expires silently at the
/// end of its block, and a reference is never dragged into move tracking.
pub fn is_linear(
    ty: Type,
    structs: &[StructDecl],
    enums: &[EnumDecl],
    arrays: &[ArrayDecl],
) -> bool {
    !ty.is_ref() && !is_copy(ty, structs, enums, arrays)
}

/// Whether `ty` **transitively contains** a reference — is one itself, or
/// reaches one through a struct field, an enum variant payload, or an array
/// element. The predicate every escape rejection is stated over, so a
/// reference cannot slip into storage one level down from a declaration site.
///
/// A `^T` payload is deliberately *not* followed: a cell may close a type
/// cycle (`^List` inside `List`), so following one would not terminate.
/// `check_no_stored_references` sweeps the interned cell registry directly
/// instead, which reaches every payload shape a program can name without
/// recursing.
pub(super) fn contains_reference(
    ty: Type,
    structs: &[StructDecl],
    enums: &[EnumDecl],
    arrays: &[ArrayDecl],
) -> bool {
    match ty {
        Type::Ref(..) => true,
        // P7 slice 3c (R5): a slice carries a borrow, so it is
        // reference-bearing. This is what keeps the declaration-level output
        // ban covering slices: reported reference-free, a user word could
        // declare `( -- Slice[T] )` and hand back a view of its own dead
        // frame. The element is not followed -- it is concrete and owns
        // nothing the view could nest a reference through.
        Type::Slice(..) => true,
        Type::Struct(id, _) => structs[id.index()]
            .fields
            .iter()
            .any(|(_, f)| contains_reference(*f, structs, enums, arrays)),
        Type::Enum(id, _) => enums[id.index()]
            .variants
            .iter()
            .flat_map(|v| v.fields.iter())
            .any(|(_, f)| contains_reference(*f, structs, enums, arrays)),
        Type::Array(id, _) => {
            contains_reference(arrays[id.index()].element, structs, enums, arrays)
        }
        _ => false,
    }
}

/// The shared wording for a declared **output** that transitively contains a
/// reference: `check_reference_free_signature` (`word_entry.rs`, a `Slot`
/// signature) and `check_quotation_reference_free_effect` (`captures.rs`, a
/// `QuotEffect`) both hit this, over two different row representations, so
/// the message lives once here instead of twice. `location` is empty for the
/// word-level check (unlocated, matching its sibling calls) and an
/// `in_word(ctx)` + `(line N)` suffix for the quotation-effect check, which
/// has no name of its own to cite.
pub(super) fn stored_reference_output_error(name: &str, ty: Type, location: &str) -> String {
    format!(
        "error: a reference cannot be stored: {} declares the output `{ty}`{location}\n  a `&T`/`&!T` borrows a local of the callee's own frame, which is gone by the time the caller reads it; take the reference as an input instead",
        crate::resolve::render_word(name)
    )
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::lexer::lex;

    /// Assert `name`'s rows are exactly a homogeneous `(T T -- T)` set, one
    /// per type in `want`, all lowering `lower`. Shared shape for the
    /// binary numeric-tower operators, mirroring
    /// `builtin_table_plus_has_a_row_per_numeric_type`.
    fn assert_homogeneous_binary_rows(name: &str, want: Vec<Type>, lower: BuiltinLower) {
        let table = builtin_table();
        let rows = table
            .get(name)
            .unwrap_or_else(|| panic!("`{name}` is a builtin operator"));
        assert_eq!(rows.len(), want.len(), "row count for `{name}`");
        let mut got: Vec<Type> = rows
            .iter()
            .map(|r| {
                assert_eq!(
                    r.inputs,
                    vec![r.outputs[0], r.outputs[0]],
                    "a `{name}` row is homogeneous `(T T -- T)`"
                );
                assert_eq!(r.lower, lower, "`{name}` lowers `{lower:?}`");
                r.outputs[0]
            })
            .collect();
        let mut want = want;
        got.sort_by_key(|t| t.name());
        want.sort_by_key(|t| t.name());
        assert_eq!(got, want, "one `{name}` row per expected type, no more");
    }
    /// Assert `name`'s rows are the irregular `(T, i64 -- T)` shape (the
    /// shift-amount operand is always `i64` regardless of `T`), one per
    /// `int_types()`, lowering `lower`. Nothing before slice 8a fix 4 checked
    /// that the *second* input type is right: a row wrongly shaped `(T, T --
    /// T)` would still pass `builtin_table_plus_has_a_row_per_numeric_type`-
    /// style checks that only compare `inputs[0]`/`inputs[1]` against
    /// `outputs[0]`.
    fn assert_shift_rows(name: &str, lower: BuiltinLower) {
        let table = builtin_table();
        let rows = table
            .get(name)
            .unwrap_or_else(|| panic!("`{name}` is a builtin operator"));
        let want = int_types();
        assert_eq!(rows.len(), want.len(), "row count for `{name}`");
        let mut got: Vec<Type> = rows
            .iter()
            .map(|r| {
                assert_eq!(
                    r.inputs,
                    vec![r.outputs[0], Type::I64],
                    "a `{name}` row is `(T, i64 -- T)`, the count is always `i64`"
                );
                assert_eq!(r.lower, lower, "`{name}` lowers `{lower:?}`");
                r.outputs[0]
            })
            .collect();
        let mut want = want;
        got.sort_by_key(|t| t.name());
        want.sort_by_key(|t| t.name());
        assert_eq!(got, want, "one `{name}` row per int type, no more");
    }
    #[test]
    fn builtin_table_plus_has_a_row_per_numeric_type() {
        // Q-A: `add` resolves by exact operand type, so the table carries one
        // homogeneous `(T T -- T)` row for every numeric type and nothing
        // else. Anchored to the literal count (12: eight fixed-width ints,
        // usize/isize, two floats) rather than `numeric_types()` itself, so
        // shrinking that function can't shrink both sides of the comparison
        // together and hide a wiring bug.
        let table = builtin_table();
        let rows = table.get("add").expect("`add` is a builtin operator");
        assert_eq!(rows.len(), 12, "12 numeric rows");
        let mut got: Vec<Type> = rows
            .iter()
            .map(|r| {
                assert_eq!(
                    r.inputs,
                    vec![r.outputs[0], r.outputs[0]],
                    "an `add` row is homogeneous `(T T -- T)`"
                );
                assert_eq!(r.lower, BuiltinLower::Add);
                r.outputs[0]
            })
            .collect();
        let mut want = numeric_types();
        got.sort_by_key(|t| t.name());
        want.sort_by_key(|t| t.name());
        assert_eq!(got, want, "one `add` row per numeric type, no more");
    }
    #[test]
    fn builtin_table_sub_has_a_row_per_numeric_type() {
        assert_homogeneous_binary_rows("sub", numeric_types(), BuiltinLower::Sub);
    }
    #[test]
    fn builtin_table_mul_has_a_row_per_numeric_type() {
        assert_homogeneous_binary_rows("mul", numeric_types(), BuiltinLower::Mul);
    }
    #[test]
    fn builtin_table_div_has_a_row_per_float_type() {
        // `div` is float-only (D7): the integer tower divides via a separate
        // hand-written path this table does not cover.
        assert_homogeneous_binary_rows("div", float_types(), BuiltinLower::DivFloat);
    }
    #[test]
    fn builtin_table_mod_has_a_row_per_int_type() {
        assert_homogeneous_binary_rows("mod", int_types(), BuiltinLower::Mod);
    }
    #[test]
    fn builtin_table_max_has_a_row_per_int_type() {
        // `max` is integer-only: `max-total` is the float twin (D7).
        assert_homogeneous_binary_rows("max", int_types(), BuiltinLower::Max);
    }
    #[test]
    fn builtin_table_max_total_has_a_row_per_float_type() {
        assert_homogeneous_binary_rows("max-total", float_types(), BuiltinLower::MaxTotal);
    }
    #[test]
    fn builtin_table_and_has_a_row_per_int_type() {
        // `and`/`or`/`xor` are bitwise on every integer width and logical on
        // `bool` too, but the bool half is not a row here: `bool` is
        // `core::bool`'s enum, so the `Type` naming it is build-resolved while
        // this table is built once per process (P7 slice 3i R4). The table's
        // domain is exactly the integer tower; `check_operator`'s own arms
        // decide bool's membership.
        assert_homogeneous_binary_rows("and", int_types(), BuiltinLower::And);
    }
    #[test]
    fn builtin_table_or_has_a_row_per_int_type() {
        assert_homogeneous_binary_rows("or", int_types(), BuiltinLower::Or);
    }
    #[test]
    fn builtin_table_xor_has_a_row_per_int_type() {
        assert_homogeneous_binary_rows("xor", int_types(), BuiltinLower::Xor);
    }
    #[test]
    fn builtin_table_holds_no_bool_row_for_any_operator() {
        // P7 slice 3i (R4): the whole table, not just the four logical names --
        // a row whose type came from a registry position would name whatever
        // enum happened to sit there.
        for (name, rows) in builtin_table() {
            for r in rows {
                for ty in r.inputs.iter().chain(r.outputs.iter()) {
                    assert!(
                        !matches!(ty, Type::Enum(..)),
                        "`{name}` has a row naming the enum `{ty}`"
                    );
                }
            }
        }
    }
    #[test]
    fn builtin_table_not_has_a_row_per_int_type() {
        // `not` is unary, so it does not fit `assert_homogeneous_binary_rows`
        // (a `(T -- T)` shape, not `(T T -- T)`).
        let table = builtin_table();
        let rows = table.get("not").expect("`not` is a builtin operator");
        let mut want = int_types();
        assert_eq!(rows.len(), want.len(), "row count for `not`");
        let mut got: Vec<Type> = rows
            .iter()
            .map(|r| {
                assert_eq!(r.inputs, vec![r.outputs[0]], "a `not` row is `(T -- T)`");
                assert_eq!(r.lower, BuiltinLower::Not);
                r.outputs[0]
            })
            .collect();
        got.sort_by_key(|t| t.name());
        want.sort_by_key(|t| t.name());
        assert_eq!(got, want, "one `not` row per int type, no more");
    }
    #[test]
    fn builtin_table_shl_rows_take_an_i64_count_regardless_of_element_type() {
        assert_shift_rows("shl", BuiltinLower::Shl);
    }
    #[test]
    fn builtin_table_shr_rows_take_an_i64_count_regardless_of_element_type() {
        assert_shift_rows("shr", BuiltinLower::Shr);
    }
    #[test]
    fn builtin_table_comparisons_have_a_row_per_numeric_type() {
        // Slice 10c (R-P3-3): **retargeted, not deleted**. This is the only
        // thing pinning comparison coverage of the whole numeric tower, and
        // the tower rows moved wholesale from `eq`/`lt`/... to the `u`-prefixed
        // primitives. Deleting it to go green would drop the guard at exactly
        // the moment the slice puts it under strain; the surface names are now
        // `'T: Copy Ord`-polymorphic library words over these rows, whose own
        // tower coverage E-P3-4 part 4 exercises end to end.
        let table = builtin_table();
        for (op, cmp) in COMPARISON_PRIMITIVES {
            let rows = table
                .get(op)
                .unwrap_or_else(|| panic!("`{op}` is a builtin operator"));
            let want = numeric_types();
            assert_eq!(rows.len(), want.len(), "row count for `{op}`");
            let mut got: Vec<Type> = rows
                .iter()
                .map(|r| {
                    assert_eq!(r.outputs, vec![Type::U32], "`{op}` produces a `u32` flag");
                    assert_eq!(r.inputs.len(), 2, "`{op}` is binary");
                    assert_eq!(r.inputs[0], r.inputs[1], "a `{op}` row is homogeneous");
                    assert_eq!(
                        r.lower,
                        BuiltinLower::Cmp(cmp),
                        "`{op}` lowers `Cmp({cmp:?})`"
                    );
                    r.inputs[0]
                })
                .collect();
            let mut want = want;
            got.sort_by_key(|t| t.name());
            want.sort_by_key(|t| t.name());
            assert_eq!(got, want, "one `{op}` row per numeric type, no more");
        }
        for op in ["eq", "lt", "gt", "lte", "gte", "ne"] {
            assert!(
                !table.contains_key(op),
                "`{op}` left `BUILTIN_TABLE` for `lib/`; leaving a row behind \
                 both restores the builtin and re-arms the `inline` \
                 builtin-name gate against the library word"
            );
        }
    }
    // Phase 3 Slice 1: the linear core on bare linear values.

    #[test]
    fn is_copy_every_scalar_is_copy_and_a_drop_overloaded_struct_is_not() {
        // P7 slice 3i: `Bool` is `core::bool`'s enum, so it is named through
        // that registry rather than `Type::from_name`, and its entry must be
        // present for `is_copy`'s enum arm to resolve it.
        let bool_enums = crate::test_support::core_bool_enums();
        let bool_ty = resolve_bool_type(&bool_enums).expect("`core::bool` declares `Bool`");
        assert!(is_copy(bool_ty, &[], &bool_enums, &[]), "Bool is Copy");
        for name in ["i8", "u64", "f32", "f64", "usize"] {
            assert!(
                is_copy(Type::from_name(name).unwrap(), &[], &bool_enums, &[]),
                "{name} is Copy"
            );
        }
        // R3 (slice 8b): a struct with a user `drop` overload is linear
        // whatever its fields say -- built directly here since this test
        // exercises `is_copy`'s own signature, not a checked module.
        let structs = vec![StructDecl {
            name: "Res".to_string(),
            name_static: "Res",
            fields: vec![("tag".to_string(), Type::I64)],
            span: Span::default(),
            has_drop_overload: true,
            is_bundle: false,
            module: 0,
        }];
        let res = Type::Struct(StructId::from_index(0), "Res");
        assert!(!is_copy(res, &structs, &[], &[]));
    }
    #[test]
    fn is_copy_owned_cell_is_never_copy_regardless_of_payload() {
        // R4: always linear, no payload lookup, even over a Copy payload.
        let mut cells = Vec::new();
        let ty = crate::ast::intern_owned_cell_type(&mut cells, Type::I64);
        assert!(!is_copy(ty, &[], &[], &[]));
    }
    #[test]
    fn is_copy_ctor_image_is_not_copy() {
        // P7b.S1 (S1-16 gap, fixed): `Type::CtorImage` used to fall through
        // to the wildcard `_ => true` arm, making it `Copy` -- it is not a
        // concrete value type at all.
        let ty = Type::CtorImage(
            crate::ast::GenericId {
                is_enum: false,
                idx: 0,
                module: 0,
            },
            "Box",
        );
        assert!(!is_copy(ty, &[], &[], &[]));
    }
    #[test]
    fn is_copy_struct_is_linear_iff_a_field_is_transitively() {
        // R7/R8 (Phase 2): a struct with no linear field is Copy; one with a
        // linear field (direct or nested) is linear, transitively. `^i64`
        // (an owning cell, always linear regardless of payload) stands in
        // for a direct linear leaf field, since this test exercises
        // `is_copy`'s own fold directly rather than through a checked module.
        let mut owned_cells = Vec::new();
        let cell_ty = intern_owned_cell_type(&mut owned_cells, Type::I64);
        let structs = vec![
            StructDecl {
                name: "Plain".to_string(),
                name_static: "Plain",
                fields: vec![("x".to_string(), Type::I64), ("y".to_string(), Type::I64)],
                span: Span::default(),
                has_drop_overload: false,
                is_bundle: false,
                module: 0,
            },
            StructDecl {
                name: "Holds".to_string(),
                name_static: "Holds",
                fields: vec![("a".to_string(), cell_ty), ("b".to_string(), Type::I64)],
                span: Span::default(),
                has_drop_overload: false,
                is_bundle: false,
                module: 0,
            },
            StructDecl {
                name: "Wraps".to_string(),
                name_static: "Wraps",
                fields: vec![(
                    "h".to_string(),
                    Type::Struct(StructId::from_index(1), "Holds"),
                )],
                span: Span::default(),
                has_drop_overload: false,
                is_bundle: false,
                module: 0,
            },
        ];
        let plain = Type::Struct(StructId::from_index(0), "Plain");
        let holds = Type::Struct(StructId::from_index(1), "Holds");
        let wraps = Type::Struct(StructId::from_index(2), "Wraps");
        assert!(is_copy(plain, &structs, &[], &[]));
        assert!(!is_copy(holds, &structs, &[], &[]));
        assert!(!is_copy(wraps, &structs, &[], &[]));
    }
    #[test]
    fn is_copy_enum_is_linear_iff_a_variant_field_is_transitively() {
        // R7/R12 (Phase 4): an enum with no linear variant field is Copy; one
        // with a linear field (direct in one variant, or nested through a
        // struct in another) is linear, transitively. `Plain` has no linear
        // variant, `Item` carries a linear field (an owning cell) directly in
        // `Full`, `Boxed` carries one nested inside `Holds`. Built by hand
        // rather than parsed, for the same reason as the struct fold above.
        let mut owned_cells = Vec::new();
        let cell_ty = intern_owned_cell_type(&mut owned_cells, Type::I64);
        let structs = vec![StructDecl {
            name: "Holds".to_string(),
            name_static: "Holds",
            fields: vec![("a".to_string(), cell_ty), ("b".to_string(), Type::I64)],
            span: Span::default(),
            has_drop_overload: false,
            is_bundle: false,
            module: 0,
        }];
        // Reused across three enums (Plain/Item/Boxed), so it cannot embed
        // any single owning enum name; the placeholder is diagnostic-only
        // and equality-safe (R1).
        let variant = |name: &'static str, fields: Vec<(String, Type)>| VariantDecl {
            name: name.to_string(),
            name_static: name,
            display_static: name,
            fields,
            span: Span::default(),
        };
        let enums = vec![
            EnumDecl {
                name: "Plain".to_string(),
                name_static: "Plain",
                variants: vec![variant("A", vec![]), variant("B", vec![])],
                span: Span::default(),
                module: 0,
            },
            EnumDecl {
                name: "Item".to_string(),
                name_static: "Item",
                variants: vec![
                    variant("Empty", vec![]),
                    variant("Full", vec![("v".to_string(), cell_ty)]),
                ],
                span: Span::default(),
                module: 0,
            },
            EnumDecl {
                name: "Boxed".to_string(),
                name_static: "Boxed",
                variants: vec![
                    variant(
                        "Some",
                        vec![(
                            "h".to_string(),
                            Type::Struct(StructId::from_index(0), "Holds"),
                        )],
                    ),
                    variant("None", vec![]),
                ],
                span: Span::default(),
                module: 0,
            },
        ];
        let plain = Type::Enum(EnumId::from_index(0), "Plain");
        let item = Type::Enum(EnumId::from_index(1), "Item");
        let boxed = Type::Enum(EnumId::from_index(2), "Boxed");
        assert!(is_copy(plain, &structs, &enums, &[]));
        assert!(!is_copy(item, &structs, &enums, &[]));
        assert!(!is_copy(boxed, &structs, &enums, &[]));
    }
    #[test]
    fn shared_reference_is_copy_and_mutable_reference_is_neither() {
        // The soundness question here: getting either wrong silently misclassifies
        // a reference as duplicable-and-droppable, or as owing a linear drop it
        // must never receive.
        let mut refs = Vec::new();
        let shared = intern_ref_type(&mut refs, Type::I64, false);
        let mutable = intern_ref_type(&mut refs, Type::I64, true);
        assert_ne!(shared, mutable);
        assert_eq!(shared.name(), "&i64");
        assert_eq!(mutable.name(), "&!i64");

        assert!(is_copy(shared, &[], &[], &[]));
        assert!(!is_copy(mutable, &[], &[], &[]));
        // Neither is linear: a reference owns nothing, so neither enters move
        // tracking nor owes a disposal.
        assert!(!is_linear(shared, &[], &[], &[]));
        assert!(!is_linear(mutable, &[], &[], &[]));
    }
    #[test]
    fn contains_reference_sees_through_a_struct_field() {
        // The predicate is transitive: a struct that merely *reaches* a
        // reference is rejected wherever a bare one would be.
        let tokens = lex("type: Plain x i64 ;\n").unwrap();
        let module = crate::test_support::parse_with_core(&tokens).unwrap();
        let mut refs = Vec::new();
        let plain = Type::Struct(StructId::from_index(0), "Plain");
        assert!(!contains_reference(
            plain,
            &module.structs,
            &module.enums,
            &module.arrays
        ));
        let mut structs = module.structs;
        structs[0].fields.push((
            "r".to_string(),
            intern_ref_type(&mut refs, Type::I64, false),
        ));
        assert!(contains_reference(
            plain,
            &structs,
            &module.enums,
            &module.arrays
        ));
    }

    /// P7 slice 3c (R4): the mutability split, in both directions. The
    /// `_ => true` wildcard would answer `true` for both, making a mutable
    /// view freely `dup`-able and breaking exclusivity outright.
    #[test]
    fn is_copy_shared_slice_is_copy_mutable_slice_is_not() {
        let mut slices = Vec::new();
        let shared = crate::ast::intern_slice_type(&mut slices, Type::I64, false);
        let mutable = crate::ast::intern_slice_type(&mut slices, Type::I64, true);
        assert!(is_copy(shared, &[], &[], &[]));
        assert!(!is_copy(mutable, &[], &[], &[]));
        // Neither is *linear* either: a view owns nothing, so it expires
        // silently and is owed no `drop` (R12, via `is_ref`).
        assert!(!is_linear(shared, &[], &[], &[]));
        assert!(!is_linear(mutable, &[], &[], &[]));
    }

    /// P7.S3h: the marker's whole mechanism. `owning [ ... ]` is not `Copy`,
    /// so it *is* linear -- and every exactly-once obligation (move tracking,
    /// the `dup` gate, the forgotten-value error, consumed-on-every-path) is
    /// inherited from that one answer with no code of its own. The plain
    /// quotation stays `Copy`, so no program that exists today gains an
    /// obligation.
    ///
    /// Deleting the `OwningQuotation` arm drops it to the `_ => true`
    /// wildcard, which fails here: an owning closure would be freely
    /// duplicated and silently forgotten, leaking whatever it captured.
    #[test]
    fn is_copy_owning_quotation_is_linear_plain_quotation_is_copy() {
        let own = crate::ast::owning_quotation_type(vec![Type::I64], Vec::new());
        let plain = crate::ast::quotation_type(vec![Type::I64], Vec::new());
        assert!(!is_copy(own, &[], &[], &[]));
        assert!(is_linear(own, &[], &[], &[]));
        assert!(is_copy(plain, &[], &[], &[]));
        assert!(!is_linear(plain, &[], &[], &[]));
    }

    /// P7 slice 3c (R5): what keeps the declaration-level output ban covering
    /// slices. Reported reference-free, `( -- Slice[i64] )` would be admitted.
    #[test]
    fn contains_reference_true_for_slice() {
        let mut slices = Vec::new();
        let shared = crate::ast::intern_slice_type(&mut slices, Type::I64, false);
        let mutable = crate::ast::intern_slice_type(&mut slices, Type::I64, true);
        assert!(contains_reference(shared, &[], &[], &[]));
        assert!(contains_reference(mutable, &[], &[], &[]));
    }
}
