//! Builtin operator table and type predicates: `Sig`/`Overload` resolution,
//! the concrete `builtin_table()` rows `check_operator` dispatches through,
//! and `is_copy`/`is_linear`/`contains_reference`. Engine-independent leaf: no
//! `Ctx`, `Scope`, or `Moves` dependency, so nothing here can see the borrow
//! checker.

use std::collections::HashMap;

use super::*;

/// A word's typed stack effect: the concrete input and output slot types,
/// deepest-first (leftmost in `( … )` is deepest on the stack).
#[derive(Debug, Clone)]
pub struct Sig {
    pub inputs: Vec<Type>,
    pub outputs: Vec<Type>,
}

/// The typed effect of a declared word.
pub fn sig_of(effect: &StackEffect) -> Sig {
    Sig {
        inputs: effect.inputs.iter().map(|s| s.ty).collect(),
        outputs: effect.outputs.iter().map(|s| s.ty).collect(),
    }
}

#[derive(Debug, Clone)]
pub struct Overload {
    pub sig: Sig,
    pub symbol: String,
}

/// R1/R2: the one candidate among `candidates` whose declared inputs exactly
/// match `operands`, if any. R1's widened duplicate-word key guarantees at
/// most one: two candidates registered under one name in scope never share
/// input types.
pub(super) fn resolve_overload<'a>(
    candidates: &'a [Overload],
    operands: &[Type],
) -> Option<&'a Overload> {
    candidates.iter().find(|o| o.sig.inputs == operands)
}

/// One builtin overload candidate (slice 8a, Q-A): the concrete input types
/// it matches (deepest-first), the concrete outputs it produces, and the
/// codegen a call resolving to it emits.
///
/// Only `inputs`/`outputs` are load-bearing: they are what the checker's
/// dispatch reads. `lower` records which instruction each row's retired
/// `check_operator` arm produced, but nothing consumes it -- lowering reaches
/// a builtin through `lower_call`'s name-directed arms and an overload
/// through the per-`Span` resolved-symbol record, neither of which consults
/// this table. It is unused weight kept only because it documents the
/// name-to-codegen mapping; delete it, and the unit tests that only assert
/// its shape, unless a table-driven lowering actually arrives to want it.
#[derive(Debug, Clone)]
pub struct BuiltinRow {
    pub inputs: Vec<Type>,
    pub outputs: Vec<Type>,
    #[allow(dead_code)]
    pub lower: BuiltinLower,
}

/// The codegen a resolved builtin row emits: one variant per distinct
/// instruction the type-directed `check_operator` arms produced. This is why
/// a row is not a `Sig` (Q-A): several rows for one name share the
/// `(inputs, outputs)` shape but differ here (`.`'s 14 rows all lower a
/// `Print`; a future user `.` lowers a `Call`).
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum BuiltinLower {
    Add,
    Sub,
    Mul,
    DivFloat,
    Mod,
    And,
    Or,
    Xor,
    Not,
    Shl,
    Shr,
    Cmp(crate::ir::CmpOp),
    Max,
    MaxTotal,
    Print,
}

/// The numeric types the arithmetic tower and comparisons range over (the
/// eight fixed-width ints, `usize`/`isize`, and the two floats): `is_numeric`
/// made concrete as a list so the table below is generated by iteration
/// rather than hand-typed per row.
pub(super) fn numeric_types() -> Vec<Type> {
    [
        "i8", "i16", "i32", "i64", "u8", "u16", "u32", "u64", "usize", "isize", "f32", "f64",
    ]
    .iter()
    .map(|n| Type::from_name(n).expect("a builtin numeric type name"))
    .collect()
}

/// The integer subset (the eight widths plus `usize`/`isize`, D7): the domain
/// of `mod`/`and`/`or`/`xor`/`not`/`shl`/`shr`/`max`.
pub(super) fn int_types() -> Vec<Type> {
    numeric_types().into_iter().filter(|t| t.is_int()).collect()
}

/// The two float types: the domain of `/` and `max-total`.
pub(super) fn float_types() -> Vec<Type> {
    numeric_types()
        .into_iter()
        .filter(|t| t.is_float())
        .collect()
}

/// The 14 printable types `.` dispatches over: every numeric type plus
/// `str` and `cstr` (the `check_operator` `"."` predicate, cross-checked
/// against the `Instr::Print` codegen arms). `bool` is no longer among them
/// (slice 9 R6): its `.` overload is the library word
/// `bool_print_word_def` injected into every module, reached through 8a's
/// `builtin_overloads` dispatch on a builtin-row exact miss, not a row here.
pub(super) fn printable_types() -> Vec<Type> {
    let mut v = numeric_types();
    v.push(Type::Str);
    v.push(Type::Cstr);
    v
}

/// The builtin overload table (slice 8a, Q-A): every concrete row a builtin
/// operator resolves to, keyed by operator name, each name carrying one row
/// per operand-type shape it accepts. `check_operator` does an exact-type
/// lookup here first (so a user overload of a builtin name can shadow a call
/// site, phase 2); the numeric operand-class coercion and its per-operator
/// diagnostics remain a hand-written fallback reached only on an exact miss
/// (Q-B). The generic builtins (`len`/`fill`/`cstr`, the `>T` conversions,
/// the shuffles) are carved out and stay in their own dispatchers (Q-A, R0).
pub fn builtin_table() -> HashMap<String, Vec<BuiltinRow>> {
    use crate::ir::CmpOp;
    let mut table: HashMap<String, Vec<BuiltinRow>> = HashMap::new();
    let mut row = |name: &str, inputs: Vec<Type>, outputs: Vec<Type>, lower: BuiltinLower| {
        table.entry(name.to_string()).or_default().push(BuiltinRow {
            inputs,
            outputs,
            lower,
        });
    };
    for ty in numeric_types() {
        row("+", vec![ty, ty], vec![ty], BuiltinLower::Add);
        row("-", vec![ty, ty], vec![ty], BuiltinLower::Sub);
        row("*", vec![ty, ty], vec![ty], BuiltinLower::Mul);
        for (op, cmp) in [
            ("=", CmpOp::Eq),
            ("<", CmpOp::Lt),
            (">", CmpOp::Gt),
            ("<=", CmpOp::Le),
            (">=", CmpOp::Ge),
            ("<>", CmpOp::Ne),
        ] {
            row(op, vec![ty, ty], vec![Type::BOOL], BuiltinLower::Cmp(cmp));
        }
    }
    for ty in float_types() {
        row("/", vec![ty, ty], vec![ty], BuiltinLower::DivFloat);
        row("max-total", vec![ty, ty], vec![ty], BuiltinLower::MaxTotal);
    }
    for ty in int_types() {
        row("mod", vec![ty, ty], vec![ty], BuiltinLower::Mod);
        row("and", vec![ty, ty], vec![ty], BuiltinLower::And);
        row("or", vec![ty, ty], vec![ty], BuiltinLower::Or);
        row("xor", vec![ty, ty], vec![ty], BuiltinLower::Xor);
        row("not", vec![ty], vec![ty], BuiltinLower::Not);
        row("shl", vec![ty, Type::I64], vec![ty], BuiltinLower::Shl);
        row("shr", vec![ty, Type::I64], vec![ty], BuiltinLower::Shr);
        row("max", vec![ty, ty], vec![ty], BuiltinLower::Max);
    }
    // `and`/`or`/`xor`/`not` are logical on `bool` as well as bitwise on the
    // integers: a stack language evaluates both operands eagerly, so
    // bitwise-on-0/1 and logical coincide.
    row(
        "and",
        vec![Type::BOOL, Type::BOOL],
        vec![Type::BOOL],
        BuiltinLower::And,
    );
    row(
        "or",
        vec![Type::BOOL, Type::BOOL],
        vec![Type::BOOL],
        BuiltinLower::Or,
    );
    row(
        "xor",
        vec![Type::BOOL, Type::BOOL],
        vec![Type::BOOL],
        BuiltinLower::Xor,
    );
    row("not", vec![Type::BOOL], vec![Type::BOOL], BuiltinLower::Not);
    for ty in printable_types() {
        row(".", vec![ty], vec![], BuiltinLower::Print);
    }
    table
}

/// The builtin table, built once. `check_operator` consults it on every
/// operator occurrence; `builtin_table()` itself rebuilds a fresh map for the
/// callers that own theirs (the REPL, the tests).
pub(super) static BUILTIN_TABLE: std::sync::LazyLock<HashMap<String, Vec<BuiltinRow>>> =
    std::sync::LazyLock::new(builtin_table);

/// R2/R7: whether `ty` is `Copy` (freely duplicated and discarded) rather than
/// linear (used exactly once, disposed by `drop`). A struct or enum is linear
/// iff any field/variant-payload field is (transitively), so a
/// struct-of-struct-of-resource or an enum carrying one is linear too.
/// `structs`/`enums` resolve a `Type::Struct`/`Type::Enum`'s fields; neither
/// can recurse into itself (`check_recursion` rejects that first), so this
/// always terminates.
///
/// R3 (slice 8b): a struct with a user `drop` overload is linear whatever its
/// fields say — a resource wrapping one `i64` would otherwise be `Copy` by
/// the structural fold alone, and so silently duplicated and forgotten.
pub fn is_copy(ty: Type, structs: &[StructDecl], enums: &[EnumDecl], arrays: &[ArrayDecl]) -> bool {
    match ty {
        Type::Struct(id, _) if structs[id.index()].has_drop_overload => false,
        Type::Struct(id, _) => structs[id.index()]
            .fields
            .iter()
            .all(|(_, field_ty)| is_copy(*field_ty, structs, enums, arrays)),
        Type::Enum(id, _) => enums[id.index()]
            .variants
            .iter()
            .flat_map(|v| v.fields.iter())
            .all(|(_, field_ty)| is_copy(*field_ty, structs, enums, arrays)),
        Type::Array(id, _) => is_copy(arrays[id.index()].element, structs, enums, arrays),
        // Always linear regardless of payload, so no payload lookup here.
        Type::OwnedCell(_, _) => false,
        // A shared reference is freely duplicated and discarded; a mutable one
        // is not (the exclusivity rule, which `dup`'s Copy gate already enforces).
        Type::Ref(_, mutable, _) => !mutable,
        _ => true,
    }
}

/// Whether `ty` carries an exactly-once obligation: used exactly once,
/// disposed by `drop`, tracked by `Moves`. This is *not* the negation of
/// `is_copy`: `&!T` is neither `Copy` nor linear, so it is duplicated
/// by nothing and owed to nothing — a reference local expires silently at the
/// end of its block, and a reference is never dragged into move tracking.
pub fn is_linear(
    ty: Type,
    structs: &[StructDecl],
    enums: &[EnumDecl],
    arrays: &[ArrayDecl],
) -> bool {
    !ty.is_ref() && !is_copy(ty, structs, enums, arrays)
}

/// Whether `ty` **transitively contains** a reference — is one itself, or
/// reaches one through a struct field, an enum variant payload, or an array
/// element. The predicate every escape rejection is stated over, so a
/// reference cannot slip into storage one level down from a declaration site.
///
/// A `^T` payload is deliberately *not* followed: a cell may close a type
/// cycle (`^List` inside `List`), so following one would not terminate.
/// `check_no_stored_references` sweeps the interned cell registry directly
/// instead, which reaches every payload shape a program can name without
/// recursing.
pub(super) fn contains_reference(
    ty: Type,
    structs: &[StructDecl],
    enums: &[EnumDecl],
    arrays: &[ArrayDecl],
) -> bool {
    match ty {
        Type::Ref(..) => true,
        Type::Struct(id, _) => structs[id.index()]
            .fields
            .iter()
            .any(|(_, f)| contains_reference(*f, structs, enums, arrays)),
        Type::Enum(id, _) => enums[id.index()]
            .variants
            .iter()
            .flat_map(|v| v.fields.iter())
            .any(|(_, f)| contains_reference(*f, structs, enums, arrays)),
        Type::Array(id, _) => {
            contains_reference(arrays[id.index()].element, structs, enums, arrays)
        }
        _ => false,
    }
}
