//! Builtin operator table and type predicates: `Sig`/`Overload` resolution,
//! the concrete `builtin_table()` rows `check_operator` dispatches through,
//! and `is_copy`/`is_linear`/`contains_reference`. Engine-independent leaf: no
//! `Ctx`, `Scope`, or `Moves` dependency, so nothing here can see the borrow
//! checker.

use std::collections::HashMap;

use super::*;

/// A word's typed stack effect: the concrete input and output slot types,
/// deepest-first (leftmost in `( … )` is deepest on the stack).
#[derive(Debug, Clone)]
pub struct Sig {
    pub inputs: Vec<Type>,
    pub outputs: Vec<Type>,
}

/// The typed effect of a declared word.
pub fn sig_of(effect: &StackEffect) -> Sig {
    Sig {
        inputs: effect.inputs.iter().map(|s| s.ty).collect(),
        outputs: effect.outputs.iter().map(|s| s.ty).collect(),
    }
}

#[derive(Debug, Clone)]
pub struct Overload {
    pub sig: Sig,
    pub symbol: String,
}

/// R1/R2: the one candidate among `candidates` whose declared inputs exactly
/// match `operands`, if any. R1's widened duplicate-word key guarantees at
/// most one: two candidates registered under one name in scope never share
/// input types.
pub(super) fn resolve_overload<'a>(
    candidates: &'a [Overload],
    operands: &[Type],
) -> Option<&'a Overload> {
    candidates.iter().find(|o| o.sig.inputs == operands)
}

/// One builtin overload candidate (slice 8a, Q-A): the concrete input types
/// it matches (deepest-first), the concrete outputs it produces, and the
/// codegen a call resolving to it emits.
///
/// Only `inputs`/`outputs` are load-bearing: they are what the checker's
/// dispatch reads. `lower` records which instruction each row's retired
/// `check_operator` arm produced, but nothing consumes it -- lowering reaches
/// a builtin through `lower_call`'s name-directed arms and an overload
/// through the per-`Span` resolved-symbol record, neither of which consults
/// this table. It is unused weight kept only because it documents the
/// name-to-codegen mapping; delete it, and the unit tests that only assert
/// its shape, unless a table-driven lowering actually arrives to want it.
#[derive(Debug, Clone)]
pub struct BuiltinRow {
    pub inputs: Vec<Type>,
    pub outputs: Vec<Type>,
    #[allow(dead_code)]
    pub lower: BuiltinLower,
}

/// The codegen a resolved builtin row emits: one variant per distinct
/// instruction the type-directed `check_operator` arms produced. This is why
/// a row is not a `Sig` (Q-A): several rows for one name share the
/// `(inputs, outputs)` shape but differ here (`.`'s 14 rows all lower a
/// `Print`; a future user `.` lowers a `Call`).
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum BuiltinLower {
    Add,
    Sub,
    Mul,
    DivFloat,
    Mod,
    And,
    Or,
    Xor,
    Not,
    Shl,
    Shr,
    Cmp(crate::ir::CmpOp),
    Max,
    MaxTotal,
    Print,
}

/// The numeric types the arithmetic tower and comparisons range over (the
/// eight fixed-width ints, `usize`/`isize`, and the two floats): `is_numeric`
/// made concrete as a list so the table below is generated by iteration
/// rather than hand-typed per row.
pub(super) fn numeric_types() -> Vec<Type> {
    [
        "i8", "i16", "i32", "i64", "u8", "u16", "u32", "u64", "usize", "isize", "f32", "f64",
    ]
    .iter()
    .map(|n| Type::from_name(n).expect("a builtin numeric type name"))
    .collect()
}

/// The integer subset (the eight widths plus `usize`/`isize`, D7): the domain
/// of `mod`/`and`/`or`/`xor`/`not`/`shl`/`shr`/`max`.
pub(super) fn int_types() -> Vec<Type> {
    numeric_types().into_iter().filter(|t| t.is_int()).collect()
}

/// The two float types: the domain of `/` and `max-total`.
pub(super) fn float_types() -> Vec<Type> {
    numeric_types()
        .into_iter()
        .filter(|t| t.is_float())
        .collect()
}

/// The 14 printable types `.` dispatches over: every numeric type plus
/// `str` and `cstr` (the `check_operator` `"."` predicate, cross-checked
/// against the `Instr::Print` codegen arms). `bool` is no longer among them
/// (slice 9 R6): its `.` overload is the library word
/// `bool_print_word_def` injected into every module, reached through 8a's
/// `builtin_overloads` dispatch on a builtin-row exact miss, not a row here.
pub(super) fn printable_types() -> Vec<Type> {
    let mut v = numeric_types();
    v.push(Type::Str);
    v.push(Type::Cstr);
    v
}

/// The builtin overload table (slice 8a, Q-A): every concrete row a builtin
/// operator resolves to, keyed by operator name, each name carrying one row
/// per operand-type shape it accepts. `check_operator` does an exact-type
/// lookup here first (so a user overload of a builtin name can shadow a call
/// site, phase 2); the numeric operand-class coercion and its per-operator
/// diagnostics remain a hand-written fallback reached only on an exact miss
/// (Q-B). The generic builtins (`len`/`fill`/`cstr`, the `>T` conversions,
/// the shuffles) are carved out and stay in their own dispatchers (Q-A, R0).
pub fn builtin_table() -> HashMap<String, Vec<BuiltinRow>> {
    use crate::ir::CmpOp;
    let mut table: HashMap<String, Vec<BuiltinRow>> = HashMap::new();
    let mut row = |name: &str, inputs: Vec<Type>, outputs: Vec<Type>, lower: BuiltinLower| {
        table.entry(name.to_string()).or_default().push(BuiltinRow {
            inputs,
            outputs,
            lower,
        });
    };
    for ty in numeric_types() {
        row("+", vec![ty, ty], vec![ty], BuiltinLower::Add);
        row("-", vec![ty, ty], vec![ty], BuiltinLower::Sub);
        row("*", vec![ty, ty], vec![ty], BuiltinLower::Mul);
        for (op, cmp) in [
            ("=", CmpOp::Eq),
            ("<", CmpOp::Lt),
            (">", CmpOp::Gt),
            ("<=", CmpOp::Le),
            (">=", CmpOp::Ge),
            ("<>", CmpOp::Ne),
        ] {
            row(op, vec![ty, ty], vec![Type::BOOL], BuiltinLower::Cmp(cmp));
        }
    }
    for ty in float_types() {
        row("/", vec![ty, ty], vec![ty], BuiltinLower::DivFloat);
        row("max-total", vec![ty, ty], vec![ty], BuiltinLower::MaxTotal);
    }
    for ty in int_types() {
        row("mod", vec![ty, ty], vec![ty], BuiltinLower::Mod);
        row("and", vec![ty, ty], vec![ty], BuiltinLower::And);
        row("or", vec![ty, ty], vec![ty], BuiltinLower::Or);
        row("xor", vec![ty, ty], vec![ty], BuiltinLower::Xor);
        row("not", vec![ty], vec![ty], BuiltinLower::Not);
        row("shl", vec![ty, Type::I64], vec![ty], BuiltinLower::Shl);
        row("shr", vec![ty, Type::I64], vec![ty], BuiltinLower::Shr);
        row("max", vec![ty, ty], vec![ty], BuiltinLower::Max);
    }
    // `and`/`or`/`xor`/`not` are logical on `bool` as well as bitwise on the
    // integers: a stack language evaluates both operands eagerly, so
    // bitwise-on-0/1 and logical coincide.
    row(
        "and",
        vec![Type::BOOL, Type::BOOL],
        vec![Type::BOOL],
        BuiltinLower::And,
    );
    row(
        "or",
        vec![Type::BOOL, Type::BOOL],
        vec![Type::BOOL],
        BuiltinLower::Or,
    );
    row(
        "xor",
        vec![Type::BOOL, Type::BOOL],
        vec![Type::BOOL],
        BuiltinLower::Xor,
    );
    row("not", vec![Type::BOOL], vec![Type::BOOL], BuiltinLower::Not);
    for ty in printable_types() {
        row(".", vec![ty], vec![], BuiltinLower::Print);
    }
    table
}

/// The builtin table, built once. `check_operator` consults it on every
/// operator occurrence; `builtin_table()` itself rebuilds a fresh map for the
/// callers that own theirs (the REPL, the tests).
pub(super) static BUILTIN_TABLE: std::sync::LazyLock<HashMap<String, Vec<BuiltinRow>>> =
    std::sync::LazyLock::new(builtin_table);

/// R2/R7: whether `ty` is `Copy` (freely duplicated and discarded) rather than
/// linear (used exactly once, disposed by `drop`). A struct or enum is linear
/// iff any field/variant-payload field is (transitively), so a
/// struct-of-struct-of-resource or an enum carrying one is linear too.
/// `structs`/`enums` resolve a `Type::Struct`/`Type::Enum`'s fields; neither
/// can recurse into itself (`check_recursion` rejects that first), so this
/// always terminates.
///
/// R3 (slice 8b): a struct with a user `drop` overload is linear whatever its
/// fields say — a resource wrapping one `i64` would otherwise be `Copy` by
/// the structural fold alone, and so silently duplicated and forgotten.
pub fn is_copy(ty: Type, structs: &[StructDecl], enums: &[EnumDecl], arrays: &[ArrayDecl]) -> bool {
    match ty {
        Type::Struct(id, _) if structs[id.index()].has_drop_overload => false,
        Type::Struct(id, _) => structs[id.index()]
            .fields
            .iter()
            .all(|(_, field_ty)| is_copy(*field_ty, structs, enums, arrays)),
        Type::Enum(id, _) => enums[id.index()]
            .variants
            .iter()
            .flat_map(|v| v.fields.iter())
            .all(|(_, field_ty)| is_copy(*field_ty, structs, enums, arrays)),
        Type::Array(id, _) => is_copy(arrays[id.index()].element, structs, enums, arrays),
        // Always linear regardless of payload, so no payload lookup here.
        Type::OwnedCell(_, _) => false,
        // A shared reference is freely duplicated and discarded; a mutable one
        // is not (the exclusivity rule, which `dup`'s Copy gate already enforces).
        Type::Ref(_, mutable, _) => !mutable,
        _ => true,
    }
}

/// Whether `ty` carries an exactly-once obligation: used exactly once,
/// disposed by `drop`, tracked by `Moves`. This is *not* the negation of
/// `is_copy`: `&!T` is neither `Copy` nor linear, so it is duplicated
/// by nothing and owed to nothing — a reference local expires silently at the
/// end of its block, and a reference is never dragged into move tracking.
pub fn is_linear(
    ty: Type,
    structs: &[StructDecl],
    enums: &[EnumDecl],
    arrays: &[ArrayDecl],
) -> bool {
    !ty.is_ref() && !is_copy(ty, structs, enums, arrays)
}

/// Whether `ty` **transitively contains** a reference — is one itself, or
/// reaches one through a struct field, an enum variant payload, or an array
/// element. The predicate every escape rejection is stated over, so a
/// reference cannot slip into storage one level down from a declaration site.
///
/// A `^T` payload is deliberately *not* followed: a cell may close a type
/// cycle (`^List` inside `List`), so following one would not terminate.
/// `check_no_stored_references` sweeps the interned cell registry directly
/// instead, which reaches every payload shape a program can name without
/// recursing.
pub(super) fn contains_reference(
    ty: Type,
    structs: &[StructDecl],
    enums: &[EnumDecl],
    arrays: &[ArrayDecl],
) -> bool {
    match ty {
        Type::Ref(..) => true,
        Type::Struct(id, _) => structs[id.index()]
            .fields
            .iter()
            .any(|(_, f)| contains_reference(*f, structs, enums, arrays)),
        Type::Enum(id, _) => enums[id.index()]
            .variants
            .iter()
            .flat_map(|v| v.fields.iter())
            .any(|(_, f)| contains_reference(*f, structs, enums, arrays)),
        Type::Array(id, _) => {
            contains_reference(arrays[id.index()].element, structs, enums, arrays)
        }
        _ => false,
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::lexer::lex;
    use crate::parser::parse;

    /// Assert `name`'s rows are exactly a homogeneous `(T T -- T)` set, one
    /// per type in `want`, all lowering `lower`. Shared shape for the
    /// binary numeric-tower operators, mirroring
    /// `builtin_table_plus_has_a_row_per_numeric_type`.
    fn assert_homogeneous_binary_rows(name: &str, want: Vec<Type>, lower: BuiltinLower) {
        let table = builtin_table();
        let rows = table
            .get(name)
            .unwrap_or_else(|| panic!("`{name}` is a builtin operator"));
        assert_eq!(rows.len(), want.len(), "row count for `{name}`");
        let mut got: Vec<Type> = rows
            .iter()
            .map(|r| {
                assert_eq!(
                    r.inputs,
                    vec![r.outputs[0], r.outputs[0]],
                    "a `{name}` row is homogeneous `(T T -- T)`"
                );
                assert_eq!(r.lower, lower, "`{name}` lowers `{lower:?}`");
                r.outputs[0]
            })
            .collect();
        let mut want = want;
        got.sort_by_key(|t| t.name());
        want.sort_by_key(|t| t.name());
        assert_eq!(got, want, "one `{name}` row per expected type, no more");
    }
    /// Assert `name`'s rows are the irregular `(T, i64 -- T)` shape (the
    /// shift-amount operand is always `i64` regardless of `T`), one per
    /// `int_types()`, lowering `lower`. Nothing before slice 8a fix 4 checked
    /// that the *second* input type is right: a row wrongly shaped `(T, T --
    /// T)` would still pass `builtin_table_plus_has_a_row_per_numeric_type`-
    /// style checks that only compare `inputs[0]`/`inputs[1]` against
    /// `outputs[0]`.
    fn assert_shift_rows(name: &str, lower: BuiltinLower) {
        let table = builtin_table();
        let rows = table
            .get(name)
            .unwrap_or_else(|| panic!("`{name}` is a builtin operator"));
        let want = int_types();
        assert_eq!(rows.len(), want.len(), "row count for `{name}`");
        let mut got: Vec<Type> = rows
            .iter()
            .map(|r| {
                assert_eq!(
                    r.inputs,
                    vec![r.outputs[0], Type::I64],
                    "a `{name}` row is `(T, i64 -- T)`, the count is always `i64`"
                );
                assert_eq!(r.lower, lower, "`{name}` lowers `{lower:?}`");
                r.outputs[0]
            })
            .collect();
        let mut want = want;
        got.sort_by_key(|t| t.name());
        want.sort_by_key(|t| t.name());
        assert_eq!(got, want, "one `{name}` row per int type, no more");
    }
    #[test]
    fn builtin_table_plus_has_a_row_per_numeric_type() {
        // Q-A: `+` resolves by exact operand type, so the table carries one
        // homogeneous `(T T -- T)` row for every numeric type and nothing
        // else. Anchored to the literal count (12: eight fixed-width ints,
        // usize/isize, two floats) rather than `numeric_types()` itself, so
        // shrinking that function can't shrink both sides of the comparison
        // together and hide a wiring bug.
        let table = builtin_table();
        let rows = table.get("+").expect("`+` is a builtin operator");
        assert_eq!(rows.len(), 12, "12 numeric rows");
        let mut got: Vec<Type> = rows
            .iter()
            .map(|r| {
                assert_eq!(
                    r.inputs,
                    vec![r.outputs[0], r.outputs[0]],
                    "a `+` row is homogeneous `(T T -- T)`"
                );
                assert_eq!(r.lower, BuiltinLower::Add);
                r.outputs[0]
            })
            .collect();
        let mut want = numeric_types();
        got.sort_by_key(|t| t.name());
        want.sort_by_key(|t| t.name());
        assert_eq!(got, want, "one `+` row per numeric type, no more");
    }
    #[test]
    fn builtin_table_sub_has_a_row_per_numeric_type() {
        assert_homogeneous_binary_rows("-", numeric_types(), BuiltinLower::Sub);
    }
    #[test]
    fn builtin_table_mul_has_a_row_per_numeric_type() {
        assert_homogeneous_binary_rows("*", numeric_types(), BuiltinLower::Mul);
    }
    #[test]
    fn builtin_table_div_has_a_row_per_float_type() {
        // `/` is float-only (D7): the integer tower divides via a separate
        // hand-written path this table does not cover.
        assert_homogeneous_binary_rows("/", float_types(), BuiltinLower::DivFloat);
    }
    #[test]
    fn builtin_table_mod_has_a_row_per_int_type() {
        assert_homogeneous_binary_rows("mod", int_types(), BuiltinLower::Mod);
    }
    #[test]
    fn builtin_table_max_has_a_row_per_int_type() {
        // `max` is integer-only: `max-total` is the float twin (D7).
        assert_homogeneous_binary_rows("max", int_types(), BuiltinLower::Max);
    }
    #[test]
    fn builtin_table_max_total_has_a_row_per_float_type() {
        assert_homogeneous_binary_rows("max-total", float_types(), BuiltinLower::MaxTotal);
    }
    #[test]
    fn builtin_table_and_has_a_row_per_int_type_plus_bool() {
        // `and`/`or`/`xor` are bitwise on every integer width and logical on
        // `bool` (eager evaluation makes bitwise-on-0/1 coincide with
        // logical), so their domain is `int_types()` plus one `bool` row.
        let mut want = int_types();
        want.push(Type::BOOL);
        assert_homogeneous_binary_rows("and", want, BuiltinLower::And);
    }
    #[test]
    fn builtin_table_or_has_a_row_per_int_type_plus_bool() {
        let mut want = int_types();
        want.push(Type::BOOL);
        assert_homogeneous_binary_rows("or", want, BuiltinLower::Or);
    }
    #[test]
    fn builtin_table_xor_has_a_row_per_int_type_plus_bool() {
        let mut want = int_types();
        want.push(Type::BOOL);
        assert_homogeneous_binary_rows("xor", want, BuiltinLower::Xor);
    }
    #[test]
    fn builtin_table_not_has_a_row_per_int_type_plus_bool() {
        // `not` is unary, so it does not fit `assert_homogeneous_binary_rows`
        // (a `(T -- T)` shape, not `(T T -- T)`).
        let table = builtin_table();
        let rows = table.get("not").expect("`not` is a builtin operator");
        let mut want = int_types();
        want.push(Type::BOOL);
        assert_eq!(rows.len(), want.len(), "row count for `not`");
        let mut got: Vec<Type> = rows
            .iter()
            .map(|r| {
                assert_eq!(r.inputs, vec![r.outputs[0]], "a `not` row is `(T -- T)`");
                assert_eq!(r.lower, BuiltinLower::Not);
                r.outputs[0]
            })
            .collect();
        got.sort_by_key(|t| t.name());
        want.sort_by_key(|t| t.name());
        assert_eq!(got, want, "one `not` row per int type plus `bool`, no more");
    }
    #[test]
    fn builtin_table_shl_rows_take_an_i64_count_regardless_of_element_type() {
        assert_shift_rows("shl", BuiltinLower::Shl);
    }
    #[test]
    fn builtin_table_shr_rows_take_an_i64_count_regardless_of_element_type() {
        assert_shift_rows("shr", BuiltinLower::Shr);
    }
    #[test]
    fn builtin_table_comparisons_have_a_row_per_numeric_type() {
        use crate::ir::CmpOp;
        let table = builtin_table();
        for (op, cmp) in [
            ("=", CmpOp::Eq),
            ("<", CmpOp::Lt),
            (">", CmpOp::Gt),
            ("<=", CmpOp::Le),
            (">=", CmpOp::Ge),
            ("<>", CmpOp::Ne),
        ] {
            let rows = table
                .get(op)
                .unwrap_or_else(|| panic!("`{op}` is a builtin operator"));
            let want = numeric_types();
            assert_eq!(rows.len(), want.len(), "row count for `{op}`");
            let mut got: Vec<Type> = rows
                .iter()
                .map(|r| {
                    assert_eq!(r.outputs, vec![Type::BOOL], "`{op}` produces `bool`");
                    assert_eq!(r.inputs.len(), 2, "`{op}` is binary");
                    assert_eq!(r.inputs[0], r.inputs[1], "a `{op}` row is homogeneous");
                    assert_eq!(
                        r.lower,
                        BuiltinLower::Cmp(cmp),
                        "`{op}` lowers `Cmp({cmp:?})`"
                    );
                    r.inputs[0]
                })
                .collect();
            let mut want = want;
            got.sort_by_key(|t| t.name());
            want.sort_by_key(|t| t.name());
            assert_eq!(got, want, "one `{op}` row per numeric type, no more");
        }
    }
    #[test]
    fn builtin_table_has_a_row_per_printable_type_for_print() {
        // Rule 6: `.` dispatches over 14 printable types, each a `(T -- )` row
        // lowering a `Print`. Mutation-check: dropping the printable loop or a
        // `push` in `printable_types` fails this. `bool` is not among them
        // (slice 9 R6): it dispatches through the injected library overload.
        let table = builtin_table();
        let rows = table.get(".").expect("`.` is a builtin operator");
        assert_eq!(rows.len(), 14, "14 printable rows");
        let mut got: Vec<Type> = rows
            .iter()
            .map(|r| {
                assert_eq!(r.outputs, Vec::<Type>::new(), "`.` produces nothing");
                assert_eq!(r.lower, BuiltinLower::Print);
                assert_eq!(r.inputs.len(), 1, "`.` is unary");
                r.inputs[0]
            })
            .collect();
        let mut want = printable_types();
        got.sort_by_key(|t| t.name());
        want.sort_by_key(|t| t.name());
        assert_eq!(got, want);
    }
    // Phase 3 Slice 1: the linear core on bare linear values.

    #[test]
    fn is_copy_every_scalar_is_copy_and_a_drop_overloaded_struct_is_not() {
        // `bool` is `Type::Enum(BOOL_ENUM_ID, ..)` (Slice 9): its registry
        // entry must be present, exactly as `assemble_module`/the REPL
        // session seed it, for `is_copy`'s enum arm to resolve it.
        let bool_enums = [crate::ast::bool_enum_decl()];
        for name in ["i8", "u64", "f32", "f64", "bool", "usize"] {
            assert!(
                is_copy(Type::from_name(name).unwrap(), &[], &bool_enums, &[]),
                "{name} is Copy"
            );
        }
        // R3 (slice 8b): a struct with a user `drop` overload is linear
        // whatever its fields say -- built directly here since this test
        // exercises `is_copy`'s own signature, not a checked module.
        let structs = vec![StructDecl {
            name: "Res".to_string(),
            name_static: "Res",
            fields: vec![("tag".to_string(), Type::I64)],
            span: Span::default(),
            has_drop_overload: true,
            is_bundle: false,
            module: 0,
        }];
        let res = Type::Struct(StructId::from_index(0), "Res");
        assert!(!is_copy(res, &structs, &[], &[]));
    }
    #[test]
    fn is_copy_owned_cell_is_never_copy_regardless_of_payload() {
        // R4: always linear, no payload lookup, even over a Copy payload.
        let mut cells = Vec::new();
        let ty = crate::ast::intern_owned_cell_type(&mut cells, Type::I64);
        assert!(!is_copy(ty, &[], &[], &[]));
    }
    #[test]
    fn is_copy_struct_is_linear_iff_a_field_is_transitively() {
        // R7/R8 (Phase 2): a struct with no linear field is Copy; one with a
        // linear field (direct or nested) is linear, transitively. `^i64`
        // (an owning cell, always linear regardless of payload) stands in
        // for a direct linear leaf field, since this test exercises
        // `is_copy`'s own fold directly rather than through a checked module.
        let mut owned_cells = Vec::new();
        let cell_ty = intern_owned_cell_type(&mut owned_cells, Type::I64);
        let structs = vec![
            StructDecl {
                name: "Plain".to_string(),
                name_static: "Plain",
                fields: vec![("x".to_string(), Type::I64), ("y".to_string(), Type::I64)],
                span: Span::default(),
                has_drop_overload: false,
                is_bundle: false,
                module: 0,
            },
            StructDecl {
                name: "Holds".to_string(),
                name_static: "Holds",
                fields: vec![("a".to_string(), cell_ty), ("b".to_string(), Type::I64)],
                span: Span::default(),
                has_drop_overload: false,
                is_bundle: false,
                module: 0,
            },
            StructDecl {
                name: "Wraps".to_string(),
                name_static: "Wraps",
                fields: vec![(
                    "h".to_string(),
                    Type::Struct(StructId::from_index(1), "Holds"),
                )],
                span: Span::default(),
                has_drop_overload: false,
                is_bundle: false,
                module: 0,
            },
        ];
        let plain = Type::Struct(StructId::from_index(0), "Plain");
        let holds = Type::Struct(StructId::from_index(1), "Holds");
        let wraps = Type::Struct(StructId::from_index(2), "Wraps");
        assert!(is_copy(plain, &structs, &[], &[]));
        assert!(!is_copy(holds, &structs, &[], &[]));
        assert!(!is_copy(wraps, &structs, &[], &[]));
    }
    #[test]
    fn is_copy_enum_is_linear_iff_a_variant_field_is_transitively() {
        // R7/R12 (Phase 4): an enum with no linear variant field is Copy; one
        // with a linear field (direct in one variant, or nested through a
        // struct in another) is linear, transitively. `Plain` has no linear
        // variant, `Item` carries a linear field (an owning cell) directly in
        // `Full`, `Boxed` carries one nested inside `Holds`. Built by hand
        // rather than parsed, for the same reason as the struct fold above.
        let mut owned_cells = Vec::new();
        let cell_ty = intern_owned_cell_type(&mut owned_cells, Type::I64);
        let structs = vec![StructDecl {
            name: "Holds".to_string(),
            name_static: "Holds",
            fields: vec![("a".to_string(), cell_ty), ("b".to_string(), Type::I64)],
            span: Span::default(),
            has_drop_overload: false,
            is_bundle: false,
            module: 0,
        }];
        let variant = |name: &'static str, fields: Vec<(String, Type)>| VariantDecl {
            name: name.to_string(),
            name_static: name,
            fields,
            span: Span::default(),
        };
        let enums = vec![
            EnumDecl {
                name: "Plain".to_string(),
                name_static: "Plain",
                variants: vec![variant("A", vec![]), variant("B", vec![])],
                span: Span::default(),
                module: 0,
            },
            EnumDecl {
                name: "Item".to_string(),
                name_static: "Item",
                variants: vec![
                    variant("Empty", vec![]),
                    variant("Full", vec![("v".to_string(), cell_ty)]),
                ],
                span: Span::default(),
                module: 0,
            },
            EnumDecl {
                name: "Boxed".to_string(),
                name_static: "Boxed",
                variants: vec![
                    variant(
                        "Some",
                        vec![(
                            "h".to_string(),
                            Type::Struct(StructId::from_index(0), "Holds"),
                        )],
                    ),
                    variant("None", vec![]),
                ],
                span: Span::default(),
                module: 0,
            },
        ];
        let plain = Type::Enum(EnumId::from_index(0), "Plain");
        let item = Type::Enum(EnumId::from_index(1), "Item");
        let boxed = Type::Enum(EnumId::from_index(2), "Boxed");
        assert!(is_copy(plain, &structs, &enums, &[]));
        assert!(!is_copy(item, &structs, &enums, &[]));
        assert!(!is_copy(boxed, &structs, &enums, &[]));
    }
    #[test]
    fn shared_reference_is_copy_and_mutable_reference_is_neither() {
        // The soundness question here: getting either wrong silently misclassifies
        // a reference as duplicable-and-droppable, or as owing a linear drop it
        // must never receive.
        let mut refs = Vec::new();
        let shared = intern_ref_type(&mut refs, Type::I64, false);
        let mutable = intern_ref_type(&mut refs, Type::I64, true);
        assert_ne!(shared, mutable);
        assert_eq!(shared.name(), "&i64");
        assert_eq!(mutable.name(), "&!i64");

        assert!(is_copy(shared, &[], &[], &[]));
        assert!(!is_copy(mutable, &[], &[], &[]));
        // Neither is linear: a reference owns nothing, so neither enters move
        // tracking nor owes a disposal.
        assert!(!is_linear(shared, &[], &[], &[]));
        assert!(!is_linear(mutable, &[], &[], &[]));
    }
    #[test]
    fn contains_reference_sees_through_a_struct_field() {
        // The predicate is transitive: a struct that merely *reaches* a
        // reference is rejected wherever a bare one would be.
        let tokens = lex("type: Plain x i64 ;\n").unwrap();
        let module = parse(&tokens).unwrap();
        let mut refs = Vec::new();
        let plain = Type::Struct(StructId::from_index(0), "Plain");
        assert!(!contains_reference(
            plain,
            &module.structs,
            &module.enums,
            &module.arrays
        ));
        let mut structs = module.structs;
        structs[0].fields.push((
            "r".to_string(),
            intern_ref_type(&mut refs, Type::I64, false),
        ));
        assert!(contains_reference(
            plain,
            &structs,
            &module.enums,
            &module.arrays
        ));
    }
}
